### ISSUE TITLE
new go1.9 math/bits package

### ISSUE THREAD

**Issue by glycerine** [RoaringBitmap/roaring#101]
The go 1.9 beta 1, out today, in its release notes, says

> New bit manipulation package
>
> Go 1.9 includes a new package, math/bits, with optimized implementations for manipulating bits. On most architectures functions in this package are additionally recognized by the compiler and treated as intrinsics for additional performance.

references:

https://github.com/golang/go/blob/master/src/math/bits/bits.go

https://github.com/golang/go/issues/18616

Comment: For many if not all of these bit operations, roaring already has optimized implementations of them. Nonetheless, at a future point once go1.9 has become standard, it may be beneficial in terms of portability and performance to move to the new math/bits standard library package. Especially since the compiler treating them as intrinsics on most architectures may give some nice speedups due to better inlining/less function call overhead.

**Comment by lemire** [comment]
Related to https://github.com/RoaringBitmap/roaring/issues/97

**Comment by lemire** [comment]
Go 1.9 is out!

**Comment by lemire** [comment]
Anybody wants to have a look?

The harder part, it seems, would be to run benchmarks to make sure that we do improve the performance.

Ideally, if we could get rid of our assembly... that'd be great.

https://golang.org/pkg/math/bits/

**Comment by lemire** [comment]
Resolved.
