### ISSUE TITLE
Simple go get also fetches real-roaring-datasets

### ISSUE THREAD

**Issue by nochso** [RoaringBitmap/roaring#102]
Running `go get -v github.com/RoaringBitmap/roaring` also clones `https://github.com/RoaringBitmap/real-roaring-datasets` even though I didn't use `go get -t`.

In my opinion it should only be fetched when using `go get -t`. Perhaps you could remove it from `.gitmodules` and simply import it in your tests?

It would be nice to avoid the 120MB of ZIP files when merely using this package.

**Comment by lemire** [comment]
Good observation. Do you have an idea on how to make this work?

We have that real-roaring-datasets is not a Go package, so it never gets imported. 

I suppose we could create a Go package that includes real-roaring-datasets and provide some functions only needed as part of the tests?

**Comment by lemire** [comment]
cc @glycerine

**Comment by nochso** [comment]
I can't find any mention or use of the datasets. They're fetched, but that's it. Might as well remove it from `.gitmodules` but keep it in the makefile?

**Comment by lemire** [comment]
You are right. Let us remove them.

**Comment by glycerine** [comment]
This does seem undesirable. I seem to recall that I moved them into their own repo, and perhaps we had concerns at that point about backwards compatibility, but I see no reason not to separate them if possible.

**Comment by lemire** [comment]
Right. So I am going to delete the submodule.

**Comment by lemire** [comment]
Ok. I am closing this as the issue should be resolved. Reopen if there is an issue remaining.

**Comment by nochso** [comment]
After deleting anything under RoaringBitmap a `go get` was fast and tests pass.

Thank you.
