### ISSUE TITLE
Benchmark Or functions computing union of ~100 large sparse bitmaps

### ISSUE THREAD

**Issue by maciej** [RoaringBitmap/roaring#113]
The goal of this task is to write benchmark that will take ~100 generated sparse bitmaps and compute their unions using existing aggregation methods: `ParOr`, `FastOr`, …

**Comment by lemire** [comment]
Right. I have written a naive benchmark... https://github.com/lemire/gobitmapbenchmark It is not good enough to assess performance seriously.

One needs to balance such benchmarks with benchmarks where we have long runs of values.  That is, we need to test all container types, and their interactions.

We have a fairly complete benchmark that we use for both the C and Java version : 

https://github.com/RoaringBitmap/CBitmapCompetition

You can find the data (as text files) there...

https://github.com/RoaringBitmap/CRoaring/tree/edc6fe04a26c43267b9e87efeb1f18d7945f8ae4/benchmarks/realdata

It tests many edge cases. 

It is not hard to implement.

Note that we can benchmark against the C implementation : 
https://github.com/RoaringBitmap/gocroaring

**Comment by maciej** [comment]
I think #137 covers that well enough.

**Comment by lemire** [comment]
Indeed.
