### ISSUE TITLE
Align internal run container representation with serialized format

### ISSUE THREAD

**Issue by maciej** [RoaringBitmap/roaring#122]
Currently run container data is represented as an `[]interval16`, which is defined as
```go
type interval16 struct {
	start uint16
	last  uint16
}
```
This differs from the representation of a serialized bitmap as described [here](https://github.com/RoaringBitmap/RoaringFormatSpec). In effect it makes it hard/impossible to implement no-copy bitmap reading. I propose changing this representation to address that.

See also #116 and discussion in #37.

**Comment by lemire** [comment]
👍

**Comment by maciej** [comment]
I've started working on this in [maciej/rle-branch](https://github.com/maciej/roaring/tree/rle-len). My implementation plan is as follows:
- [x] introduce _length_ field to the existing `interval16` struct
- [ ] rewrite `interval16` struct creation in test code to be using `newInterval16FromStartLast` function instead
- [ ] progressively fix tests and code up to a point where tests pass with the bigger `interval16`
- [ ] remove `last` field from `interval16`
- [ ] fix code and tests that were broken by that removal
- [ ] fix serialization

(I'll keep updating this list as I progress with work)

**Comment by lemire** [comment]
Excellent.

**Comment by glycerine** [comment]
Well I suppose it would be the acme of foolishness to point out that it would be faster to just add another serialization format option that does match the [start, last] format and do reader-makes-right lazy correction only if needed (here I duck the flying tomatoes :)

Either way I wish this effort well. I know that it is a big effort.  I found it much easier to reason about [start, last] when getting correctness, as the corner cases are many and subtle. Revisit my comments on crossing bin boundaries in #37 and be sure to add tests cases for that situation if it does turn out out to be a hazard.

When you are testing for correctness, be sure to run extra trials by extending the `n` and `ntrial` values in the test suite (reference [1] and [2] below).  Running these with big values caught alot of corner cases in my origin implementation, but are too slow to leave on for every day/every commit test runs.

[1] https://github.com/RoaringBitmap/roaring/blob/master/rle16_test.go#L325

[2] https://github.com/RoaringBitmap/roaring/blob/master/rlei_test.go#L1616

**Comment by maciej** [comment]
@glycerine thank you for the pieces of advice! As I'll move forward with the code I'll certainly use them. :-)

Yes, if Go roaring was the only implementation and cross-language and backward compatibility was not an issue I'd definitely consider changing the spec. It's not the case, though. There are multiple implementation, another revision of the spec would need to be published. Conversion tools. Good reasoning why anyone using the current serialized format should move to the new revision. Does not seem like a faster path! :-)

**Comment by lemire** [comment]
> When you are testing for correctness, be sure to run extra trials by extending the n and ntrial values in the test suite (reference [1] and [2] below). Running these with big values caught alot of corner cases in my original implementation, but are too slow (I would let them run for a half hour before I was completely convinced) to leave big for every day/every commit test runs.

It is slightly unfortunate that we cannot automate these more thorough tests. Having the developer hack the tests on his/her local machine is not ideal.
