### ISSUE TITLE
Support 64-bit indices?

### ISSUE THREAD

**Issue by pwaller** [RoaringBitmap/roaring#136]
If it isn't already (- I may have missed it), are there any plans to support 64 bit indices ala `Roaring64NavigableMap` from the java implementation? Is it hard to do in practice?

**Comment by lemire** [comment]
To my knowledge, there is no ongoing work nor any plan in this respect. Pull Requests invited.

**Comment by maciej** [comment]
@pwaller it's a topic that has been discussed recently on Gophers Slack #performance channel: https://gophers.slack.com/archives/C0VP8EF3R/p1516279819000174
You can follow the discussion to see the current state of Go Roaring implementations and their support for 64bit values or workarounds for lack of.

@e-dard also expressed interest in 64bit values in Roaring bitmaps. Perhaps with a lot of interest someone could be able to contribute the necessary code. :-)

**Comment by lemire** [comment]
@maciej Thanks for correcting me.

**Comment by sirajmansour** [comment]
Now that this is supported in the java implementation, are there any plans to port it here :) ?

**Comment by lemire** [comment]
We have certainly not received any pull request. I am not aware of any public development on this front, though I think Pilosa has a 64-bit implementation and it is certainly open source.

**Comment by hyprnick** [comment]
@lemire Any suggestions on how best to approach getting this added?  I use this project but have not looked at the internals.  Thanks!

**Comment by lemire** [comment]
@hyprnick 

1. We have Java and C++ implementations. If you read these languages I can point you to them...

2. Pilosa’s own implementation of roaring handles 64-bit keys...

So there are implementations one can study and learn from... 

We also have an academic paper... in French... https://r-libre.teluq.ca/930/1/Roaring64bits.pdf

**Comment by evanoberholster** [comment]
Is there any process on a 64bit version?

**Comment by lemire** [comment]
I still have it as a work-in-progress. Are you interested in helping?

**Comment by evanoberholster** [comment]
@lemire Thanks for asking. Unfortunately I don't think that I have enough experience to implement what needs to still be done.
