### ISSUE TITLE
Parallel aggregation: split work by ranges of container keys

### ISSUE THREAD

**Issue by maciej** [RoaringBitmap/roaring#140]
Currently all work handed of to goroutines handling container-level aggregation is prepared in the caller goroutine  by picking a new _work unit_ from a heap. Private benchmarks (I hope to replicate the results using the public datasets) show that operating on the heap takes a fair amount of time limiting the parallelism level and taking CPU time that could otherwise be spent on the aggregation. Especially `ParAnd` could benefit from a solution that would not use the heap, as pointed out in #110.

Here is an informal description of how a `ParOr` could look like: for the given list of bitmaps _B_ lets take the smallest _Ks_ and largest _Ke_ key. Let's split the _[Ks, Ke]_ range into _N_ non-overlapping ranges. _Ks_ and _Ke_ can be computed in O(B) time.  _N_ can be determined based on the number of available CPU cores/goroutines (x * CPU count, I'd start with x anywhere between 2 and 16) and size of the range (perhaps it does not make sense to make the range 1 or 2 container long). This will be subject to fine-tuning.
Having those subranges we can then operate on them in the same manner as `FastOR` function would, but limited on a range of keys.
Results of the work units could be easily concatenated into a single `roaringArray`.

It's an open question if that would be faster, however I think it's a promising approach. :-) The idea is somehow inspired by the discussions on [RoaringBitmap#42](https://github.com/RoaringBitmap/RoaringBitmap/issues/42) and my limited understanding of how splitterator works.

**Comment by maciej** [comment]
I've implemented a straw-man version of this algorithm [here](https://github.com/RoaringBitmap/roaring/compare/master...maciej:par2), note that the diff also contains changes in #139, #143 and #145.

The benchmark results are mixed:
```
benchmark                                           old ns/op     new ns/op     delta
BenchmarkRealDataParOr/census-income_srt-8          256362        397908        +55.21%
BenchmarkRealDataParOr/census-income-8              402991        844957        +109.67%
BenchmarkRealDataParOr/census1881_srt-8             681492        610989        -10.35%
BenchmarkRealDataParOr/census1881-8                 671609        943513        +40.49%
BenchmarkRealDataParOr/dimension_003-8              7023029       1701535       -75.77%
BenchmarkRealDataParOr/dimension_008-8              3125520       627528        -79.92%
BenchmarkRealDataParOr/dimension_033-8              454973        582128        +27.95%
BenchmarkRealDataParOr/uscensus2000-8               1894956       1306723       -31.04%
BenchmarkRealDataParOr/weather_sept_85_srt-8        355695        305122        -14.22%
BenchmarkRealDataParOr/weather_sept_85-8            1297255       3762398       +190.03%
BenchmarkRealDataParOr/wikileaks-noquotes_srt-8     284867        200606        -29.58%
BenchmarkRealDataParOr/wikileaks-noquotes-8         334317        333337        -0.29%
```

**Comment by maciej** [comment]
After tweaking how the algorithm tunes itself in terms of key range splitting I'm getting consistently better results compared to the current `ParOr` implementation:
```
benchmark                                           old ns/op     new ns/op     delta
BenchmarkRealDataParOr/census-income_srt-8          259335        172584        -33.45%
BenchmarkRealDataParOr/census-income-8              397086        265200        -33.21%
BenchmarkRealDataParOr/census1881_srt-8             684741        373293        -45.48%
BenchmarkRealDataParOr/census1881-8                 671148        554907        -17.32%
BenchmarkRealDataParOr/dimension_003-8              7115701       2052883       -71.15%
BenchmarkRealDataParOr/dimension_008-8              3146326       782683        -75.12%
BenchmarkRealDataParOr/dimension_033-8              465209        196961        -57.66%
BenchmarkRealDataParOr/uscensus2000-8               1858806       1190955       -35.93%
BenchmarkRealDataParOr/weather_sept_85_srt-8        360252        144065        -60.01%
BenchmarkRealDataParOr/weather_sept_85-8            1238413       1102745       -10.95%
BenchmarkRealDataParOr/wikileaks-noquotes_srt-8     298012        111480        -62.59%
BenchmarkRealDataParOr/wikileaks-noquotes-8         339464        145425        -57.16%
```

**Comment by cakey** [comment]
Internally on our benchmarks when unioning a ton of small bitmaps, we saw a lot of overhead from maintaining the heap. We got better performance by special casing all small bitmaps (e.g. < 500 cardinality) and then directly NextMany/AddMany those values, and then ParOr'ing the remainder bitmaps that have actually expensive unions.

Perhaps worth looking into?

**Comment by lemire** [comment]
@cakey   If  NextMany/AddMany is faster than ``FastAggregator.or``, then I would consider this to be a performance bug. Can you please open an issue?

**Comment by lemire** [comment]
@maciej  These numbers are great.

**Comment by cakey** [comment]
@lemire Sure I'll see if I can reproduce with a simple benchmark.

**Comment by lemire** [comment]
@cakey  And, to be clear, roaring does support in-place operations. Please benchmark against these: https://github.com/RoaringBitmap/roaring/blob/master/fastaggregation.go#L156-L194

**Comment by maciej** [comment]
@cakey perhaps you'd be interested in giving a try of the new algorithm. I tentatively called the function "ParNaiveOr". It's available at [my roaring fork, branch par2](https://github.com/RoaringBitmap/roaring/compare/master...maciej:par2). I'd be curious if it's faster not only with the public dataset we're using but also in real-world systems. :-)
