### ISSUE TITLE
Consider loop tiling/unrolling for *bitmapContainer.lazyIORArray

### ISSUE THREAD

**Issue by maciej** [RoaringBitmap/roaring#144]
CRoaring counterpart of the `*bitmapContainer.lazyIORArray` processes 4 array elements in one loop iteration, see [bitset_util.c](https://github.com/RoaringBitmap/CRoaring/blob/f4720d05bc9620b003bd89d46fdf98d718ea7811/src/bitset_util.c#L761)

Experiment with using the same technique here.

**Comment by lemire** [comment]
Yes. It is a form of unrolling that the compiler might not do.

**Comment by lemire** [comment]
Solved.
