### ISSUE TITLE
Tests should be written using one uniform idiom

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/roaring#146]
We have Convey tests, go1.7 subtests, and basic tests. It works fine, but it is a bit unpleasant.

**Comment by alldroll** [comment]
I would like to take this issue. Does anyone have any objections if I will use Convey tests as a uniform test framework? I found it ideal for this package.

**Comment by lemire** [comment]
Let us discuss this.

Hopefully, you can explain to me what I am missing. I will give you my point of view. Please understand that my opinion is just one opinion and that I am quite willing to admit that I am wrong.

The primary use for tests, for me, is CI. So the tests run and if one fails, I need to look at the log (online, in a remote container). On rare occasions, when we add tests, or must investigate a failing test, I will issue a command line to run specific tests (maybe just one). If I need to do substantial work, I will launch an IDE. Evidently, I also run specific benchmarks.

With this in mind... here is how I view things.

Standard Go tests: 

- They are standard, simple and fast. It is easy to spot the offending test in CI.
- IDEs parse and recognize the tests, so you can run them using a graphical user interface, see where the failures are and launch specific tests.

Convey tests:

- They fill the screen (stdout) with useless strings, slowing down the tests and making it hard for the user to see where the eventual problems are. The performance impact is real: stdout is not fast. When something fails in CI, we have to scroll to find the offending tests and... importantly, Convey entirely gets in the way: it does not provide any value. Its reports are less usable than the standard tests. 
 
I realize the Convey can be used as web service, via a browser. For me, specifically, this is a useless feature. If I need a graphical interface, I am probably in an IDE in any case. Otherwise, I am probably either in a CI container or at the command line. I am really puzzled as to why I would want to launch a browser to get a nice report... More critically, I don't understand why Convey can't provide a nice and clean stdout output.

The Go Convey page claims that the console output is understandable by human beings. I don't understand this claim.

One application of Convey, apparently, is to run tests continuously... but that's not very practical with roaring. It is more practical to rely on CI.


There is an argument made that Convey code is cleaner than standard Go tests. Maybe but that's debatable.

**Comment by lemire** [comment]
Please have a look at the CI output...

https://travis-ci.org/RoaringBitmap/roaring/jobs/570086262

Convey really harms the usability... I cannot even understand what it is try to tell us... there are randomly located question marks... I basically try hard to ignore the Convey output...

**Comment by alldroll** [comment]
I can see where you're coming from, and definitely you are right that Standard Go tests can satisfy all package's needs. I was thinking about it too, go's tests have the ability to use subtests, sub benchmarks, and what really could help to use it is assert helpers such as https://github.com/stretchr/testify.  What do you think about it?

**Comment by lemire** [comment]
> What do you think about it?

I agree.

**Comment by glycerine** [comment]
`go test -convey-silent` should quiet the console.

**Comment by lemire** [comment]
@glycerine This certainly invalidate part of my criticism...

**Comment by lemire** [comment]
Fixed by @alldroll
