### ISSUE TITLE
Example Code won't run

### ISSUE THREAD

**Issue by dmlyons** [RoaringBitmap/roaring#151]
// computes union of the three bitmaps in parallel using 4 workers  
    ParOr(4, rb1, rb2, rb3)
    // computes intersection of the three bitmaps in parallel using 4 workers  
    ParAnd(4, rb1, rb2, rb3)

should be

    // computes union of the three bitmaps in parallel using 4 workers  
    roaring.ParOr(4, rb1, rb2, rb3)
    // computes intersection of the three bitmaps in parallel using 4 workers  
    roaring.ParAnd(4, rb1, rb2, rb3)

**Comment by lemire** [comment]
Thanks. The curse of copy-paste.

**Comment by dmlyons** [comment]
Thanks!
