### ISSUE TITLE
fatal error: fault starting with commit d6540aa

### ISSUE THREAD

**Issue by mschoch** [RoaringBitmap/roaring#153]
We just started seeing this (first in travis CI environment, and reproduced locally as well) after this commit: d6540aab65a17321470b1661bfc52da1823871e9

```
unexpected fault address 0x147c05f
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x147c05f pc=0x1058472]

goroutine 66 [running]:
runtime.throw(0x124463c, 0x5)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/panic.go:619 +0x81 fp=0xc420166c00 sp=0xc420166be0 pc=0x102a111
runtime.sigpanic()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/signal_unix.go:385 +0x273 fp=0xc420166c50 sp=0xc420166c00 pc=0x103f2c3
runtime.memmove(0x147c05f, 0x147c05d, 0x2)
	/usr/local/Cellar/go/1.10/libexec/src/runtime/memmove_amd64.s:143 +0x102 fp=0xc420166c58 sp=0xc420166c50 pc=0x1058472
github.com/RoaringBitmap/roaring.(*arrayContainer).iorArray(0xc42000a040, 0xc42000a060, 0x1174e47, 0xc4204be460)
	/Users/mschoch/go/src/github.com/RoaringBitmap/roaring/arraycontainer.go:377 +0x277 fp=0xc420166cf0 sp=0xc420166c58 pc=0x112b5c7
github.com/RoaringBitmap/roaring.(*arrayContainer).ior(0xc42000a040, 0x1270ce0, 0xc42000a060, 0x147c000, 0x126fda0)
	/Users/mschoch/go/src/github.com/RoaringBitmap/roaring/arraycontainer.go:334 +0x254 fp=0xc420166d60 sp=0xc420166cf0 pc=0x112b2f4
github.com/RoaringBitmap/roaring.(*Bitmap).Or(0xc4204be2a0, 0xc4204be460)
	/Users/mschoch/go/src/github.com/RoaringBitmap/roaring/roaring.go:781 +0x6e8 fp=0xc420166e48 sp=0xc420166d60 pc=0x1140148
github.com/blevesearch/bleve/index/scorch/segment/zap.(*SegmentBase).DocNumbers(0xc420264680, 0xc42032f3e0, 0x3, 0x3, 0x0, 0x0, 0x0)
	/Users/mschoch/go/src/github.com/blevesearch/bleve/index/scorch/segment/zap/segment.go:353 +0x1b8 fp=0xc420166ef0 sp=0xc420166e48 pc=0x1178498
github.com/blevesearch/bleve/index/scorch.(*SegmentSnapshot).DocNumbers(0xc42032f380, 0xc42032f3e0, 0x3, 0x3, 0x0, 0x0, 0x0)
	/Users/mschoch/go/src/github.com/blevesearch/bleve/index/scorch/snapshot_segment.go:107 +0x56 fp=0xc420166f40 sp=0xc420166ef0 pc=0x11a0d46
github.com/blevesearch/bleve/index/scorch.(*IndexSnapshot).DocIDReaderOnly.func1(0xc42032f3e0, 0x3, 0x3, 0xc42007aa80, 0x1, 0xc42032f380)
	/Users/mschoch/go/src/github.com/blevesearch/bleve/index/scorch/snapshot_index.go:176 +0x53 fp=0xc420166fb0 sp=0xc420166f40 pc=0x11c0143
runtime.goexit()
	/usr/local/Cellar/go/1.10/libexec/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420166fb8 sp=0xc420166fb0 pc=0x1057b01
created by github.com/blevesearch/bleve/index/scorch.(*IndexSnapshot).DocIDReaderOnly
	/Users/mschoch/go/src/github.com/blevesearch/bleve/index/scorch/snapshot_index.go:175 +0xb3
```

I'll try to dig up more context about what we're actually doing with roaring when this happens, but the same code works with earlier commits.

**Comment by mschoch** [comment]
I don't have a whole lot to add yet, roughly what we're doing is the following:

- many roaring bitmaps previously serialized to disk
- these roarings are mmap'd read-only and used
- at the point of this particular failure, we are building a new roaring, and OR'ing it with some of these mmap'd roarings

My attempt to create a stand-alone unit test that reproduces the failure has so far been unsuccessful.

One theory was that the roarings that we've mmap'd are not aligned on any particular boundaries, and possibly that causes a problem.  But again, in my unit test I've tried intentionally forcing misalignment and still haven't observed the problem.

**Comment by lemire** [comment]
Well. Then, at least, is my fault. So it simplifies things a bit!!!

Now... what did I do wrong...

**Comment by lemire** [comment]
Flagged this as both a bug and a priority.

**Comment by maciej** [comment]
@lemire I guess
at line 781 in roaring.go
https://github.com/RoaringBitmap/roaring/commit/d6540aab65a17321470b1661bfc52da1823871e9#diff-afacbf604114c3eccfff5658e0a1a72bR781

```go
rb.highlowcontainer.replaceKeyAndContainerAtIndex(pos1, s1, rb.highlowcontainer.getContainerAtIndex(pos1).ior(x2.highlowcontainer.getContainerAtIndex(pos2)), mustCopyOnWrite)
```

on the left side of the tor should be `getWriteableContainerAtIndex`

let me submit a PR.

**Comment by lemire** [comment]
@maciej 

Ok. Let us go with that!

Then, assuming that it is the correct fix, let us chat about the fact that our tests did not flag this bug.

**Comment by lemire** [comment]
@mschoch Can check that the PR https://github.com/RoaringBitmap/roaring/pull/154 fixed your issue.

We will close once you verify the fix.

Then we will worry about the fact that our unit tests are insufficient.

**Comment by mschoch** [comment]
This appears to fix the problem.  Thanks for the quick analysis and fix, we appreciate it!

**Comment by lemire** [comment]
+1
