### ISSUE TITLE
document performance benefits of "Bitmap.Clear() retains preallocated slices for faster future ops"

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/roaring#158]
Though we merged this PR https://github.com/RoaringBitmap/roaring/pull/156 we are relying on @steveyen's word that it significantly speeds things up.  I think we want actual hard numbers.

**Comment by steveyen** [comment]
doing some cross-linking - https://github.com/RoaringBitmap/roaring/pull/159

**Comment by lemire** [comment]
Great.
