### ISSUE TITLE
Test deserialization with adversarial inputs

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/roaring#160]
We have input files ``crashproneinput1``, ..., ``crashproneinput7``  that have been engineered to stress the deserialization routines (make the program crash).

https://github.com/RoaringBitmap/CRoaring/tree/master/tests/testdata

We should include them in our unit tests.

**Comment by maciej** [comment]
We should remember to test both `FromBuffer` and `ReadFrom` functions!

**Comment by lemire** [comment]
Indeed.

**Comment by dgryski** [comment]
Go-fuzz will also help with finding inputs with bad behaviour.

**Comment by dgryski** [comment]
In `fuzz.go` (or equivalent)

```
//build +gofuzz

package roaring

import "bytes"

func FuzzSerialization(data []byte) int {
	newrb := NewBitmap()
	if _, err := newrb.ReadFrom(bytes.NewReader(data)); err != nil {
		return 0
	}

	return 1
}
```

Note that because there's already a `Fuzz` function defined for `smat`, we need to pass a flag to `go-fuzz-build` to get it to call this one instead:

```
$ go-fuzz-build -func FuzzSerialization github.com/RoaringBitmap/roaring`
$ go-fuzz -bin=roaring-bin.zip -workdir=workdir
```

I applied the following patch to remove the `panic` and return an error instead:
```
diff --git a/serialization.go b/serialization.go
index b0ae8a6..30fb7ea 100644
--- a/serialization.go
+++ b/serialization.go
@@ -2,6 +2,7 @@ package roaring

 import (
        "encoding/binary"
+       "errors"
        "fmt"
        "io"

@@ -63,7 +64,7 @@ func (b *runContainer16) readFrom(stream io.Reader) (int, error) {
        }
        for i := range encRun {
                if len(by) < 2 {
-                       panic("insufficient/odd number of stored bytes, corrupted stream detected")
+                       return 0, errors.New("insufficient/odd number of stored bytes, corrupted stream detected")
                }
                encRun[i] = binary.LittleEndian.Uint16(by)
                by = by[2:]
@@ -71,7 +72,7 @@ func (b *runContainer16) readFrom(stream io.Reader) (int, error) {
        nr := int(numRuns)
        for i := 0; i < nr; i++ {
                if i > 0 && b.iv[i-1].last() >= encRun[i*2] {
-                       panic(fmt.Errorf("error: stored runContainer had runs that were not in sorted order!! (b.iv[i-1=%v].last = %v >= encRun[i=%v] = %v)", i-1, b.iv[i-1].last(), i, encRun[i*2]))
+                       return 0, fmt.Errorf("error: stored runContainer had runs that were not in sorted order!! (b.iv[i-1=%v].last = %v >= encRun[i=%v] = %v)", i-1, b.iv[i-1].last(), i, encRun[i*2])
                }
                b.iv = append(b.iv, interval16{start: encRun[i*2], length: encRun[i*2+1]})
                b.card += int64(encRun[i*2+1]) + 1
```

A few minutes of fuzzing produced some slice index out of bounds and a program hang.  I seeded the corpus with the testdata from the Go and C implementations.

**Comment by dgryski** [comment]
I will make a PR. Are you ok with changing the panics for error returns?

**Comment by lemire** [comment]
I think we will agree that errors are better than panics... when you can expect the caller to do something useful.

**Comment by lemire** [comment]
This is still open, see https://github.com/RoaringBitmap/roaring/pull/170#issuecomment-378858669 by @maciej

**Comment by lemire** [comment]
Reopened as a distinct issue: 

https://github.com/RoaringBitmap/roaring/issues/172
