### ISSUE TITLE
Drop msgpack

### ISSUE THREAD

**Issue by maciej** [RoaringBitmap/roaring#165]
As discussed in the ticket related to `Bitmap.FromBuffer` implementation we wanted to remove msgpack integration. msgpack was used as a stop-gap solution for serializing bitmaps before RoaringFormatSpec was implemented for run containers.

This *will* break API compatibility, which in turn breaks Go [import compatibility rule](https://research.swtch.com/vgo-import). I vote for making this change nonetheless.

@lemire what are you thoughts? Should we go forward with this?

**Comment by lemire** [comment]
I agree but let us launch a call-for-comments and wait at least a few days to see if there are objections.


Ping @0x4139 @bpot @brentp @glycerine @cornelk @statik @steveyen @willglynn

**Comment by lemire** [comment]
Ping @tgruben @dgryski

**Comment by dgryski** [comment]
From my point of view (having read over some commits and some bugs), I think it's probably fine to remove.  It's effectively non-standard; the current documentation warns about its experimental status. A quick GitHub search shows no other repositories using that function.  The hits that it does find are vendored copies of this roaring code.  As the behaviour isn't subtly changing, it's an *obvious* break as soon as somebody attempts to update their code.  The code will continue to be present in the repository, so they can construct their own migration path.  (Another idea that might make this nicer: before deleting all the code, move it all to a single file.  Then if somebody does need to reconstruct it, they just need to grab one file from the history and can drop it into their repository.)

If you're concerned about dropping it with no notice you could mark the routines as `Deprecated` in the godoc and remove them at a later point.  The `staticcheck` tool warns about using deprecated routines, and any large Go project is almost certainly using it.

**Comment by lemire** [comment]
@maciej How do you feel about @dgryski's deprecation idea? From the documentation:

> Sometimes a struct field, function, type, or even a whole package becomes redundant or unnecessary, but must be kept for compatibility with existing programs. To signal that an identifier should not be used, add a paragraph to its doc comment that begins with "Deprecated:" followed by some information about the deprecation. There are a few examples in the standard library.

This seems easy enough.

**Comment by maciej** [comment]
@lemire it's a very reasonable thing to do! So, yes, let's first mark Msgpack-related functions as deprecated and in the next step remove them altogether!

**Comment by lemire** [comment]
@maciej Want to issue a PR?

**Comment by maciej** [comment]
@lemire no, I'm leaving this for later. Whenever I have time I want try porting your SIMD optimisations from https://arxiv.org/abs/1709.07821.

I already looked at @stuartcarnie's roaring fork ([sgc-c2goasm](https://github.com/stuartcarnie/roaring/tree/sgc-c2goasm) branch). Unless he's interested in continuing the work I'd like to try picking it up from there. :-)

**Comment by lemire** [comment]
Marked as deprecated as of the last commit.
