### ISSUE TITLE
Fix deserialization bug exposed by #171

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/roaring#172]
This new PR https://github.com/RoaringBitmap/roaring/pull/171 exposed some bugs in our deserialization code, in the sense that we do not cleanly return errors. This was expected as these are adversarial inputs... but we should still fix it.

**Comment by maciej** [comment]
I've changed the ticket title slightly removing the URI and using the # ticket number instead. :-)

**Comment by lemire** [comment]
@maciej Your patch coupled with a sanity check seems to solve the problem. It should make the library safer to use all around. Great!

**Comment by maciej** [comment]
@lemire thank you for amending the `FromBuffer` with the sanity check!
