### ISSUE TITLE
Panic in LazyOR

### ISSUE THREAD

**Issue by oplehto** [RoaringBitmap/roaring#206]
I experienced a panic in LazyOR when doing a Flux query in InfluxDB 1.7.0~n201809270800. 
Unfortunately I was not able to replicate it so the best I can do at this point is to provide the trace:
https://gist.github.com/oplehto/285e688dbd1060019b5062f718193fda 

The query in question was fairly data intensive: 
```
time curl -XPOST -vsS -H accept:application/csv -H 'content-type:application/vnd.flux' http://influxdb:8086/v2/query -d 'from(bucket:"tg_udp/tg_udp") |> range(start: -24h) |> filter(fn: (r) => r._measurement == "jobdata" AND r._field == "mem_usage" AND r.job_owner == "svc" ) |> group(by:["svc"]) |> mean()'
```
over a database with a series cardinality of ~280 million. Typically these take a few minutes to complete.

**Comment by maciej** [comment]
^^ @e-dard

**Comment by maciej** [comment]
@oplehto I think it that it might be related to this change https://github.com/RoaringBitmap/roaring/pull/203/commits/1a1fe5577622c4f142703a296f35c23f3d9abdcf.

@e-dard does the `unsafe.Pointer` cast inside the loop work well with the garbage collector? Is that pointer rewritten if the GC decided to move the `arrayContainer.content`?

**Comment by lemire** [comment]
The failure seems to occur at line 556:

> i := uint(vc) >> 6

This is a shift by an immediate. How can it panic?

**Comment by lemire** [comment]
@oplehto Do you know which roaring release you are using? We need to know what is at the offending line if we are to have a chance to solve this issue.

I am not sure if it is done right now, but it should probably be done in any case: influxdb should depend on a fixed version of roaring.

**Comment by oplehto** [comment]
Ah, should’ve noticed that it is indeed from a fork: https://github.com/influxdata/roaring/tree/fc520f41fab6dcece280e8d4853d87a09a67f9e0

If it seems that this is the likely cause of the issue I can follow up with the influxdb folks.

**Comment by lemire** [comment]
Ok. I am going to close this, please reopen if you can trace it back to us.
