### ISSUE TITLE
Implement bit shift functions

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/roaring#208]
See http://bitmagic.io/dna-search.html

**Comment by HowJMay** [comment]
Does this one still need help?

**Comment by lemire** [comment]
It does still need help... See that Java implementation...

https://github.com/RoaringBitmap/RoaringBitmap/blob/master/RoaringBitmap/src/main/java/org/roaringbitmap/RoaringBitmap.java#L195-L264

**Comment by HowJMay** [comment]
Sorry I can't get the point why the link you provided (the bitmagic one) has connection to the code you provided. May I ask you for more explaination?

**Comment by lemire** [comment]
@HowJMay It is not very important for someone doing the implementation, except for the fact that it illustrates the motivation for the work... where a shift followed by an AND allows you to compute important results.

**Comment by HowJMay** [comment]
Sorry I have roughly browsed the code. I found there is an existed implementation of `addOffset`.
So I should use the java implementation to replace the existed implementation?

**Comment by lemire** [comment]
Right... So the current Go implementation allows you to add a positive value... but it is less general than the Java version where the offset can be negative. So we still need help, but you are correct that we have part of the support already.

**Comment by lemire** [comment]
Fixed by https://github.com/RoaringBitmap/roaring/pull/339
