### ISSUE TITLE
ReverseIterator is broken in some cases

### ISSUE THREAD

**Issue by akrylysov** [RoaringBitmap/roaring#213]
```
package main

import (
	"fmt"
	"github.com/RoaringBitmap/roaring"
)

func main() {
	b := roaring.New()
	for i := uint32(0); i < 5000; i++ {
		b.Add(i)
	}
	it := b.ReverseIterator()
	for it.HasNext() {
		fmt.Println(it.Next())
	}
}
```
In the example above I expect ReverseIterator to iterate all values but it iterates only a few of them:
```
4999
6
5
4
3
2
1
0
```

**Comment by joenall** [comment]
I can duplicate this and will look at it today.

**Comment by lemire** [comment]
@joenall Thanks Joe. Meanwhile, I have created a failing test:
https://github.com/RoaringBitmap/roaring/commit/02ea23d55f7d67a771302d1b046b97716370fbea

**Comment by lemire** [comment]
Assigned to @joenall

**Comment by joenall** [comment]
Should be fixed in current pull request.

**Comment by lemire** [comment]
Closing.

**Comment by akrylysov** [comment]
Thank you!
