### ISSUE TITLE
Request: please add a go.mod file

### ISSUE THREAD

**Issue by pwaller** [RoaringBitmap/roaring#216]
Hi! Great project.

I have a quick request, please could you add a `go.mod` to the root of your repository? Doing so significantly reduces the number of dependencies that my own project must list in its `go.mod`. If roaring lacks a `go.mod`, then my `go.mod` ends up including all of your transitive dependencies, including those through tests. It's a bit counter intuitive, but the inclusion of indirect dependencies for modules which lack a go.mod themselves facilitates reproducible builds.

The steps you need to follow are:

0) Obtain `go >= 1.11`
1) Run `go mod init github.com/RoaringBitmap/roaring`
2) Run `go mod tidy`
3) Commit `go.sum` and `go.mod`.
4) (Ideally) Make a new tagged release.

If (4) isn't manageable, steps 1-3 would go a long way. What you'll find is that you'll have some indirect dependencies listed in your go.mod. This is because some of your indirect dependencies themselves also lack a go.mod. If they later gain a `go.mod` and you run `go mod tidy` thereafter, those indirect dependencies will disappear from roaring's `go.mod`.

Note that with Go modules it is then no longer necessary to set `GOPATH`, which is a significant benefit for newcomers to go. It works even if roaring does not have a `go.mod`, but just makes the `go.mod` files a bit more unwieldy for downstream users, especially if they care about minimizing dependencies (as I do).

Thanks for reading.

**Comment by lemire** [comment]
Hopefully resolved now. Thanks for the clear and detailed instructions. Reopen if things do not look right.

**Comment by pwaller** [comment]
Thanks for the speedy fix @lemire! One last thing, if isn't too much trouble, a fix release tag (0.4.17) would be appreciated, so that the version can be referenced neatly.

Another useful command for you to know is that `go get` now manages the module rather than your `$GOPATH`, and it understands specific versions, so if you want to choose a specific version you can say `go get github.com/org/repo@master` or `go get github.com/org/repo@v1.2.3`, etc, to get a specific version. Right now anyone wanting to depend on a version with the go.mod you have just created can do so by saying `go get github.com/RoaringBitmap/roaring@master`, but it results in a dependency on `github.com/RoaringBitmap/roaring v0.4.17-0.20190312185508-8d778e47dd84` rather than `v0.4.17`.

**Comment by lemire** [comment]
I just tagged a release 0.4.17.

**Comment by lemire** [comment]
This is progress, evidently.
