### ISSUE TITLE
Fatal errors on the output of Or() when the input files were mmapped, array containers

### ISSUE THREAD

**Issue by jacksonrnewhouse** [RoaringBitmap/roaring#219]
Ran into this issue in production, where we tend to produce bitsets by Mmapping files, calling And() or Or() on them, and then releasing the bytes back. In *very* rare circumstances it seems that the result of Or(a, b) keeps a reference to the backing []byte slice. We saw this happen 2 times out of over 250,000 Or() calls. 

I've opened a PR in my fork of this repo at https://github.com/jacksonrnewhouse/roaring/pull/1/files. It has the suspect files and a test that panics. Only the final call to `union.ToArray()` fails. It doesn't require the bytes of `a` to be present, just `b`, and it can successfully compute methods that don't require inspecting the container bytes, such as `GetCardinality()`. The failure is not specific to `union.ToArray()`. `union.Or(union)`, `union.And(union)`, `union.AndCardinality(union)` will all fail as well.

This looks similar to https://github.com/RoaringBitmap/roaring/issues/153, but for arraycontainers.

**Comment by lemire** [comment]
This should be a priority.

**Comment by maciej** [comment]
That is correct. `Or(*Bitmap, *Bitmap)` will not create copies to containers that have not changed. Each of those containers will be marked for copy-on-write (see `needCopyOnWrite` slice in `roaringArray`).

In case of the bitmaps you presented it's the last one:
```go
	union := Or(a.bitmap, b.bitmap)
	fmt.Printf("%+v\n", union.highlowcontainer.needCopyOnWrite)
```

```
[false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false false true]
```

I would argue this to be correct behaviour.

However if I understand your use case you want to obtain a bitmap that does not reference the original mmaped memory. I believe this should be handled with a method on `*Bitmap`. I'm looking for naming proposals for that method. `*Bitmap.Unshadow()` perhaps?

Note that `Clone()` carries copy-on-write markers over, so it is not effective in your case.

Alternatively we could change the behaviour of `Clone()` hoping it wouldn't break anyone else's use case.

**Comment by jacksonrnewhouse** [comment]
What about a call like `flushCopyOnWrite()` that copies any containers with it still marked? This would accommodate my use case, be a tell op when not necessary and not change existing behavior.

**Comment by lemire** [comment]
Given two `newRb1` and `newRb2` memory-mapped, you can do...

```Go
	rbor1 := Or(newRb1, newRb2)
	rbor2 := rbor1.Clone()
	rbor3 := Or(newRb1.Clone(), newRb2.Clone())
```

Both `rbor2` and `rbor3` should not depend on the memory-mapped bytes. Of course, this creates copies, some of them are unnecessary. It would make sense to add a `flushCopyOnWrite` or `Unshadow` function.

Thoughts?

**Comment by lemire** [comment]
> Note that Clone() carries copy-on-write markers over, so it is not effective in your case.

I don't think that's correct. A Clone calls depends on `copyOnWrite` which defaults to `false`.

**Comment by jacksonrnewhouse** [comment]
@lemire, yeah cloning both bitmaps works, but seems sort of wasteful given that 99.99% of the time the containers will already not be backed by the memory-mapped bytes. If I'm required to Clone() to safely make use of a memory-mapped bitmap then I should probably just be constructing the bitmap through reading the file. 

The FlushCopyOnWrite() method allows me to only perform these operations when necessary, but maybe it'd be cleaner to provide a boolean method that tells me if the Or() result has copyOnWrite() containers.

**Comment by lemire** [comment]
I agree with you. 

I think FlushCopyOnWrite is unintuitive as a name. But the functionality is right.

**Comment by lemire** [comment]
Fixed thanks to a PR by @jacksonrnewhouse

**Comment by maciej** [comment]
I'm closing this ticket.
