### ISSUE TITLE
Inlining in 1.12.7 breaks arrayContainer methods

### ISSUE THREAD

**Issue by jacksonrnewhouse** [RoaringBitmap/roaring#224]
I ran into buggy behavior when trying to move from 1.11.5 to 1.12.7, which was surprising. Even more surprising, the bugs never manifested when running through the debugger, and went away when I added additional logging. I eventually discovered that running with `gcflags="-l"` made the bugs disappear. I've created a test case that fails and an amazonlinux Dockerfile that'll trigger the bug at https://github.com/jacksonrnewhouse/roaring/tree/inline. This bug also appears when running on OS X.

The bug doesn't trigger if
* You run on 1.11.5
* Run `go test -gcflags="-l" run TestComparison`
* Comment out a log line.
* Add a log line.
* Use a different function for generating the problematic containers.

**Comment by lemire** [comment]
I looked at your example... `byteSliceAsUint16Slice` does not make a copy, it is just pointer based. You have it point at an slice that is likely to be deleted or garbage collected. The result is undefined.

So I don't think that, as written, your code illustrates a bug in roaring.

**Comment by lemire** [comment]
This is used by `FromBuffer` which has the same characteristic: it does not make a copy. They are meant to be used with care: the caller is responsible to ensure that the byte array remains available and unchanged.

**Comment by jacksonrnewhouse** [comment]
The byte array needs to be available and unchanged until the containing struct is no longer needed. However, if the compiler is able to inline things such that the function is inlined into where the []byte is initialized then you can get errors. https://golang.org/pkg/reflect/#SliceHeader warns about this with "the Data field is not sufficient to guarantee the data it references will not be garbage collected". 

As you point out, the only place this function is called in public methods is FromBuffer, which is too complex to ever be inlined. However, you could imagine having a function like `BitmapFromContainerBytes(key uint16, bytes []byte)` which is simple enough to be inlined. I don't think you need to copy in order to prevent this. Adding a `runtime.KeepAlive(header.Data)` call to byteSliceAsUint16Slice prevents this from triggering. I'm not sure if this'd impact performance, and I agree that it will not currently be a problem using the public methods of the repo.

**Comment by lemire** [comment]
@jacksonrnewhouse 

I'm all for making things safer if you have an idea...

What would be the scope of `runtime.KeepAlive`? You are returning a pointer to a slice/array... if, at any point, the slice/array gets garbage collected or otherwise invalidated... then the pointer will become invalid. The problem is not limited to the scope of one function.

**Comment by jacksonrnewhouse** [comment]
I think you need to construct a "a separate, correctly typed pointer" before you free the input slice. So something like
```
func uint16SliceAsByteSlice(slice []uint16) []byte {
	// make a new slice header
	header := *(*reflect.SliceHeader)(unsafe.Pointer(&slice))

	// update its capacity and length
	header.Len *= 2
	header.Cap *= 2

        // create result slice, keep original slice alive result is created.  
        result :=  *(*[]byte)(unsafe.Pointer(&header))
        runtime.KeepAlive(slice)


	// return it
	return result
}
```
From reading of the runtime code, I don't expect this to incur any performance penalty. It should still be able to be inlined, for instance.

**Comment by lemire** [comment]
Here is what I think happens.

You have a slice that holds a region of memory A.

You construct a pointer to the memory region A.

The 'slice' goes out of scope. Go reclaims the memory region A.

You are left with a pointer that may point at the old data, or not... it depends on how quickly Go and/or the system makes use of the memory region. It may even be unmapped at any time.

**Comment by jacksonrnewhouse** [comment]
Yep, that sounds right. I'm gonna open a PR that uses keepalive to prevent it.
