### ISSUE TITLE
Select() returns different values after calling RunOptimize()

### ISSUE THREAD

**Issue by cryptix** [RoaringBitmap/roaring#236]
I supplied a test case for this issue with some example data in PR #235.

Just wanted to make sure that PR isn't a new test, it's a reproduction of a bug that I would like to have fixed or work around.

**Comment by lemire** [comment]
Fixed : https://github.com/RoaringBitmap/roaring/pull/238

New release issued.

Reopen if you can't verify.

**Comment by cryptix** [comment]
Yup, this is resolved! Thanks for the quick fix.
