### ISSUE TITLE
Implement BSI Addition

### ISSUE THREAD

**Issue by jacksonrnewhouse** [RoaringBitmap/roaring#260]
Bit Slice Indexes basically provide a map[int]int with some very fast operations. One operation that can be implemented against BSIs is addition, which basically sums up the values by key for two BSI's. This can be entirely accomplished using bitwise arithmetic. The primary functions you need are addToValues(*Bitmap) and addDigit(*Bitmap, int). pseudo-code for the inplace versions is something like
```
func (bsi *BSI) addToValues(bitmap *Bitmap) { 
    bsi.eBM.Or(bitmap)
}

func (bsi *BSI) addDigit(bitmap *Bitmap, digit i) {
    carry := roaring.And(bsi.bA[i], bitmap)
    bsi.bA[i].Xor(bitmap)
    if carry.GetCardinality() > 0 {
        addDigit(carry, i+1)
    }
}
```

**Comment by guymolinari** [comment]
This has been implemented.  I am preparing a pull request with this and some other enhancements.

**Comment by lemire** [comment]
@guymolinari Did you close the issue deliberately ?

**Comment by guymolinari** [comment]
I am testing the new feature now and will submit a pull request.  But Yes.

**Comment by lemire** [comment]
@guymolinari My proposal is to reopen the issue and close it when the PR will have been merged. Less confusing that way.

**Comment by guymolinari** [comment]
Sounds good.  Didn't know the process.   My apologies.

**Comment by lemire** [comment]
> Sounds good.  Didn't know the process.   My apologies.

Do not apologize. 

I have reopened the issue.

When creating a pull request, add "Fixes https://github.com/RoaringBitmap/roaring/issues/260" as part of your description. This will link the issue with the PR. You can also link the issue explicitly by entering it the addresses at the right locations in the web pages.

**Comment by guymolinari** [comment]
Cool.  I have written unit test coverage of the new features.   Just wanted
to do some more application testing for good measure.

**Comment by lemire** [comment]
Issue resolved by @guymolinari

**Comment by Smallhi** [comment]
@guymolinari  For BSI, the function transpose can be used for vectorization. I found the fucntion use a RoraingBitmap to return. It make me confused. Could u tell me how can we use it to  process groupBy computing? I think the return value RoraingBitmap discard the original Info.
Thanks a lot!

**Comment by guymolinari** [comment]
It is designed to transpose values in the BSI and convert those values to
columnIDs in a Bitmap.

Cheers,
Guy

**Comment by Smallhi** [comment]
@guymolinari  If you don't mind me asking，could you give me an example of how to "transpose values in the BSI and convert those values to columnIDs in a Bitmap".  That's very usefule for me!
Thanks a lot!

**Comment by guymolinari** [comment]
The best way to understand an open source project (at least one that is
properly run), is to look at the test cases.

**Comment by Smallhi** [comment]
@guymolinari  I had read and run all your code .... Thanks anyway!
