### ISSUE TITLE
Reduce repeated copies in in-place Or() method

### ISSUE THREAD

**Issue by jacksonrnewhouse** [RoaringBitmap/roaring#265]
Looking at allocations in roaring, I noticed that anytime you Or() on a copyOnWrite arraycontainer with another arraycontainer you end up doing two copies. The problematic line is https://github.com/RoaringBitmap/roaring/blob/c0e59bbf1874e4bacf2bbe3dcdf316e911055f80/roaring.go#L1009. First, getWritableContainerAtIndex() calls clone() on the arrayContainer. Then, the following ior() call will always need to make a new slice, as the cloned() slice has capacity exactly equal to the underlying arraycontainers cardinality. 

I think it might be possible to branch this call depending on whether the container in question is copyOnWrite or not, with the idea being that 

container.clone()
container.ior(otherContainer)
is slower than container.or(otherContainer)

Does this sound right? Is there a safe way to avoid the double-copy?

**Comment by lemire** [comment]
Yes. One could extend the ior, iand, ... functions so that they can take in shared containers and then process them accordingly in a more optimized manner. Obviously, this will entail a bit of extra code (maybe 100 extra lines).

The hard part is to design a benchmark that would check whether this is beneficial.

**Comment by lemire** [comment]
Let me elaborate. The implementation is easy. I can do it in five minutes. What is hard is the benchmark. And without a benchmark, it is useless to try to optimize.

**Comment by jacksonrnewhouse** [comment]
Approach I took in #277 is to have the bitmap either call `ior()` on an already writable container or `or()` together the COW container and the right container.

**Comment by jacksonrnewhouse** [comment]
This got addressed in #277
