### ISSUE TITLE
String method print -1 for  maxUint64 ?

### ISSUE THREAD

**Issue by JinLingChristopher** [RoaringBitmap/roaring#270]
`    rb1 := roaring64.BitmapOf(1, 2, 3, 4, 5, 100, 1000, math.MaxInt64)

	rb1.Add(math.MaxUint64)
	fmt.Println(rb1.String())

	if rb1.Contains(math.MaxInt64) {
		fmt.Println("Yes")
	} else {
		fmt.Println("No")
	}
`

> {1,2,3,4,5,100,1000,9223372036854775807,-1}
> Yes

As shown above, Contains can find MaxInt64, but cannot be print by the String method? 

Is this a bug for the String method?

**Comment by JinLingChristopher** [comment]
In my. personal opinion, line 199 and 209 in roaring64.go should be changed:

`
buffer.WriteString(strconv.FormatInt(int64(i.Next()), 10))
`
->

`
buffer.WriteString(strconv.FormatUint(uint64(i.Next()), 10))
`

**Comment by lemire** [comment]
@JinLingChristopher Are you willing to issue a pull request ?

I expect that you are correct.

cc @guymolinari

**Comment by JinLingChristopher** [comment]
I will fix this today, let me do it.

**Comment by lemire** [comment]
Fixed by the reporter. Thanks!
