### ISSUE TITLE
is there a count() function to count all the items in the bitmap?

### ISSUE THREAD

**Issue by gitmko0** [RoaringBitmap/roaring#274]
1. is there a count function? else
which is faster to get total numbers? 
a) iterate for next item to do counter
b) do a cardinality comparison with a full set

**Comment by lemire** [comment]
> is there a count function

There is. See `GetCardinality()`. Have you read through our first code example in the README.md file?

> iterate for next item to do counter

Do not do this. It is slow and unnecessary. 

> do a cardinality comparison with a full set

Do not do this.
