### ISSUE TITLE
Surprised there's no information on OOM / memory setting or disk backed solution in doc

### ISSUE THREAD

**Issue by gitmko0** [RoaringBitmap/roaring#276]
1. how do i set the memory size? (sorry i know it sounds kind of stupid to mention it, no idea why i find it funny when i typed out)
2. what happens when out of memory?
3. disk backed solution? e.g. flush data to disk / wal etc

**Comment by lemire** [comment]
Memory allocation is handle by the Go engine. For advanced users, we provide memory-file mapping capabilities in the library, please refer to the API.

We are always happy to receive contributions. If you wish to improve the documentation, please submit a pull request.
