### ISSUE TITLE
Vectorized union 

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/roaring#289]
We have ARM assembly for union2by2 as per https://github.com/RoaringBitmap/roaring/pull/287

It should be said that there are vectorized algorithm (hint: ARM NEON) for union routines. It appears in the C code (for SSE only but it is portable).

https://github.com/RoaringBitmap/CRoaring/blob/master/src/array_util.c#L1569-L1647

It is described in section 4.3 of the following paper:

* [Roaring Bitmaps: Implementation of an Optimized Software Library](https://arxiv.org/pdf/1709.07821.pdf), Software: Practice and Experience 48 (4), 2018

It is actually not difficult to implement. For someone that is either fluent in ARM NEON or wants to learn... it is a great  project.

**Comment by jacksonrnewhouse** [comment]
Closing this as it is a duplicate of #288

**Comment by lemire** [comment]
How did this happen? Weird.

**Comment by evanoberholster** [comment]
Would this likely have similar results in assembly with amd64?

**Comment by lemire** [comment]
@evanoberholster Possibly! PR invited!
