### ISSUE TITLE
Potential bug in AndAny function

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/roaring#309]
This line in AndAny looks suspicious...

https://github.com/RoaringBitmap/roaring/blob/c3410353258d6aa6dc9a4d5589fa364806eac322/fastaggregation.go#L305

The `ior` call could return a new container.

**Comment by lemire** [comment]
@jacksonrnewhouse vouched for this code. Closing.

**Comment by jacksonrnewhouse** [comment]
I mean, my vouching was just that the code was correct *given the current container implementations*. It definitely isn't correct given the general contract for ior(). I have a fix I'm about to post.

**Comment by lemire** [comment]
+1

**Comment by Oppen** [comment]
If the fix was merged, shouldn't the issue be closed?

**Comment by lemire** [comment]
Closing.
