### ISSUE TITLE
BitSliceIndexing BSI sub-library correctly stores twos complement values but range comparisons fail for negative values.

### ISSUE THREAD

**Issue by guymolinari** [RoaringBitmap/roaring#315]
Negative values are correctly stored and retrieved, however when performing any comparisons LT, GT, GE, LE, RANGE against negative values they fail horribly.

**Comment by lemire** [comment]
@guymolinari Couldn't we document that we are supporting only non-negative values? That was my expectation.

**Comment by guymolinari** [comment]
Daniel,
    I just checked in a fix for this.   What do you think?

I'm also going to add min() and max() functions.   I need this stuff.
Guy

**Comment by guymolinari** [comment]
fixed long ago.
