### ISSUE TITLE
Support CRoaring's frozen format for interoperability

### ISSUE THREAD

**Issue by Oppen** [RoaringBitmap/roaring#318]
Doing this would mean the pure Go implementation can be used to create bitmaps to later be used by a more restricted environment, such as one using Python or C, while still being able to memory map the contents.
Using the pure Go version introduces several advantages versus using GoCRoaring, such as better memory accounting and parallel operations, as well as the ability to use scratch-images when deploying in Docker.
Is there any interest in this functionality? I could try to implement it, I just want to know if it'll be rejected in principle.

Note this isn't about performance and there will be a penalty; there would be a comment in the documentation noting that this should only be used for interoperability, never where performance matters.

**Comment by lemire** [comment]
I believe it is a great idea. I do not expect that there will be a significant penalty.

To ensure compatibility, it could be useful to include an actual binary file in frozen state as part of the tests.

**Comment by Oppen** [comment]
Gotcha!

**Comment by lemire** [comment]
For people reading this: if one claims "compatibility" then one has to test with actual files...

**Comment by Oppen** [comment]
I have some untested code already. When it works, the idea is that it will support both for serialization and deserialization to work in little endian, big endian and "native" endian (i.e., if you don't clarify what you mean, it will assume the platform's endianness is what's desired). For testing I plan to convert the real data bitmaps with a simple gocroaring program, include its source in the repo and both compile natively to my x86 based system and cross-compile to PowerPC and run in qemu. This way I can generate little and big endian files. Those will also be in the repo.
The endianness thing is because frozen bitmaps are generated to be compatible with the platform that's creating them, so proper interoperability necessitates supporting both. My approach is to simply copy the buffer with proper inversion of endianness depending on the type of the correspondent field.

Does any of that make sense?

**Comment by Oppen** [comment]
Note the current code is only for reading. Because it always needs the last 4 bytes for the cookie first I will only implement support for creating them from byte slices. It will always end up storing the whole thing in one slice. Although someone may want to make a mutable version that doesn't require COW when something comes from memory, that could still be done by just unflagging it, the buffer will live more time than needed but nothing bad should happen aside from that.

**Comment by lemire** [comment]
@Oppen Right... so...

1. Only reading (immutable). That goes without saying...
2. I am not actually sure we need to even support big-endian. It would be fine, as far as I am concerned, if the code just failed on big endian systems (ideally, failed loudly, with a panic). They are becoming vanishingly rare. I expect we do not have one user of this library with a big endian system.

**Comment by Oppen** [comment]
Sounds good. That makes it much simples.

**Comment by Oppen** [comment]
As for serialization, the test I have in mind is generating the bitmaps from real data and comparing the results with the ones stored. It isn't the most robust because some containers can either be runs or bitsets/arrays, but I can just try both with and without runs and check that one of them match.

**Comment by Oppen** [comment]
Or I could have both kind of files and explicitly compare with pairs with runs and pairs without them.

**Comment by lemire** [comment]
Yeah. It is not possible to have perfect tests, but if you construct a sensible example and test that, you should catch most problems.

**Comment by Oppen** [comment]
Update. I've got serialization working locally. Deserialization gives different results, so I need to keep working on it.
I tested on the whole real datasets and wrote a little test with `testing/quick`. I also wrote benchmarks, but I'm not buying the values I get, I think the compiler is optimizing out my calls (I get absurdly low times and 0 allocs when they are at plain sight).

Would it make sense to have serialization and deserialization sent in different PRs?
Tangentially related, I  think it could be interesting to try [gopter](github.com/leanovate/gopter) to do a bit of property testing for this. Is it OK to add a dev dependency?

**Comment by lemire** [comment]
@Oppen Dependencies are not a problem, but I am not a fan of property testing for projects like roaring. Hand-crafted tests where you reason through the desired outcomes from the specification and check that it is what you get are preferable. Fuzz testing is great, but it is just an automated approach toward hand-crafted tests (where the desired outcome is computed separately).

**Comment by lemire** [comment]
@Oppen Also we worked hard to get the tests to run fast. For a long time, running the tests could take minutes because we were using an inefficient framework. It is really bad. We want fast tests. Property tests can often be several times slower than hand-crafted tests. It adds up.

**Comment by Oppen** [comment]
OK, I finished a basic round of tests. The issue I'm having is that the `Equals` method returns `false` for some reason, while `ToArray` does produce the same result for the original bitmaps and the deserialized ones.
I believe the bitmap containers do an optimization where they resize the slice to exclude the last empty values to reduce iterations in some operations, but since `bitmapEquals` checks the sizes match and my deserialization slices the whole 1024 words the comparison evaluates to `false`. I'm failing to find the place where that happens to confirm, and specially if there's a function to make that adjustment without writing it inline myself.

@lemire do you know about that?

**Comment by Oppen** [comment]
OK, it wasn't that. `Equals` receives an empty interface. I was creating the object to deserialize to as an instance of `Bitmap` rather than a pointer. It doesn't compare correctly when passed an instance rather than a pointer. Should that be considered a bug?

**Comment by Oppen** [comment]
I'll send the PR after some cleanups, but tests are passing for real data, quickcheck and a few handcrafted tests.

**Comment by lemire** [comment]
>   It doesn't compare correctly when passed an instance rather than a pointer. Should that be considered a bug?

The current implementation is this...

```
// Equals returns true if the two bitmaps contain the same integers
func (rb *Bitmap) Equals(o interface{}) bool {
	srb, ok := o.(*Bitmap)
	if ok {
		return srb.highlowcontainer.equals(rb.highlowcontainer)
	}
	return false
}
```

The most obvious way to determine whether that's correct would be to examine current practices and check whether we deviate from it.

**Comment by lemire** [comment]
> I'll send the PR after some cleanups, but tests are passing for real data, quickcheck and a few handcrafted tests.

Bravo.
