### ISSUE TITLE
Can't deserialize very big maps

### ISSUE THREAD

**Issue by pforemski** [RoaringBitmap/roaring#325]
Hi,

I found that with certain sets of a few hundred million members (eg. 250M+), you often end up with the maximum number of containers, 65536, or 0xFFFF + 1. I was surprised I couldn't de-serialize such big bitmaps, which resulted in no errors, but no data.

I found a bug that I fixed https://github.com/RoaringBitmap/roaring/pull/324

Best regards from @farsightsec :) Keep up the great work!

**Comment by Oppen** [comment]
Closing because you already fixed it. Thank you!

**Comment by lemire** [comment]
@Oppen Thanks for closing!
