### ISSUE TITLE
[suggestion]: implement non-container-optimizing operations

### ISSUE THREAD

**Issue by Oppen** [RoaringBitmap/roaring#326]
Many in-place operations convert between container types for efficiency. This makes a lot of sense when the operation involves only two containers/bitmaps, because you would want an optimal container at the end. However, multiple container operations would probably benefit from using a single accumulator container appropriate for the given task for most of the operation to avoid overloading the GC. For example, a bitset may be appropriate for operating on many containers at a time, but since we would need for them to interact with other container types we risk conversion between them. For this to be viable we would need to avoid these conversions altogether in these cases. So, the idea would be to, for example, have an `or` implementation for bitsets where any container simply accumulates its present values on it, without ever changing it to, for example, an RLE16 container.
I am not sure if those conversions tend to stabilize as we iterate over more containers tho.

**Comment by lemire** [comment]
> So, the idea would be to, for example, have an or implementation for bitsets where any container simply accumulates its present values on it, without ever changing it to, for example, an RLE16 container.

Why don't the lazy OR functions suit this need?

https://github.com/RoaringBitmap/roaring/blob/ff33c3b226c3ac033bf1a0b0f3ed647fc9cd2efa/bitmapcontainer.go#L451-L486

Note that we always leave the bitmaps in a good state after a user-visible operation, so lazy operations are for internal use only.

We do not want to expose container types as part of our public API: users should not have to worry about the internal implementation.

**Comment by Oppen** [comment]
I thought they only saved the cardinality computing step, I didn't even think of those 🤦 
I think I can close this one then, I can always reopen it if I find them unsuitable.

**Comment by lemire** [comment]
> I thought they only saved the cardinality computing step

Generally, the idea is that they are 'lazy' and try to do as little work as possible while optimizing for the scenario where you are going to re-aggregate the container soon.
