### ISSUE TITLE
Serialize frozen bitmaps to `io.Writer`

### ISSUE THREAD

**Issue by Oppen** [RoaringBitmap/roaring#332]
I just realized my original implementation of `FreezeTo` to a buffer is less than ideal for scenarios where we want to chain IO or simply write directly to files, as it needlessly creates a bigger buffer. I stumbled into this when I realized I simply write to a tar file and the standard library only exposes readers and writers for them, and it expects you to do everything sequentially.

Implementing it with an `io.Writer` argument should be rather simple, with a few compromises.
The issue is mostly about whether it is a good idea to keep the name and change the interface or to add a new function (tentatively named `WriteFrozenTo`).
The pro of renaming is we avoid duplicating logic. The cons are 1) that we either iterate the containers three times or require an `io.WriterAt` rather than an `io.Writer`, compromising either performance compared to the current implementation or flexibility; and 2) breaking an already public API (although it's most likely only used by me for now, and I can fix my projects).

Opinions?
@lemire what do you think?

**Comment by lemire** [comment]
1. It is often best to illustrate a problem with some code, maybe paired with a benchmark. Don’t optimize before you measure.
2. We need to preserve backward compatibility as much as possible. Some people have come to depend on the format as is. If it ever changed, we would need to offer a transition path, at the very least.
3. Performance questions are best answered with prototypes and benchmarks. But you definitely do not want to do many syscalls when doing IO. Working over pointers and large buffers is often the best approach. APIs like C++ streams and the Java IO API are antipatterns.

**Comment by Oppen** [comment]
1. Fair point.
2. So, if implemented, a new method is the best path. Note the format won't be changed (at least it's not what I'm proposing), but the API my previous PR exposed. In any case, keeping compatibility is more or less free.
3. That's true. However, `io.Writer`s are not necessarily making many syscalls. For example, I could implement a writer over a memory mapped file (true, I can just pass the buffer in general, but the tar example makes that quite convoluted), or I can have an adequately sized internal buffer without potentially allocating a 100MB one. I may just be chainloading to a compressor, then uploading to S3. Using S3 as an example is in part because it does benefit a bit from doing several syscalls (concurrent multipart upload can be used to saturate the NIC, but intrinsically requires many more syscalls, about 1.5k in my case) anyway, in part because it's the end goal of my use case. At the end of the day, what I'm trying to save myself is from having to choose to either reimplement tar to allow arbitrarily advancing the cursor after serializing to an already mmapped file or performing an extra alloc and copy in an already immense data set. Being able to just `Write` the containers and keys and all that an letting tar pass that through to my buffer would be desirable.

For 1., I'd like to have something like this pseudocode:
```go
type MmapFile struct{
    mmap []byte // Created with unix.Mmap
    file *os.File // Backing file; keep the pointer to truncate when needed
    cur int // Current cursor position
}

func NewMmapFile(fname string, int szHint) (MmapFile, error) {
    // Create the file, truncate to a reasonable size (szHint if > -1, for example), memory map it
}

func (mf *MmapFile) Write(buf []byte) (...) {
    if mf.cur+len(buf) > len(mf.mmap) {
        // Grow file and remap
    }
    copy(mf.mmap[mf.cur:], buf)
    mf.cur += len(buf)
    return ...
}

func uploadBitmaps(bitmaps []*roaring.Bitmap) {
    mmap := NewMmapFile(...) // Some file, if willing to precompute sizes I could have a reasonable upper bound
    gzW := gzip.NewWriter(mmap)
    trW := tar.NewWriter(gzW)
    hdr := tar.Header{}

    for _, bitmap := range bitmaps {
        hdr.Name = ...
        hdr.Size = bitmap.GetFrozenSize()
        trW.WriteHeader(&hdr)
        // Current implementation requires:
        buf, _ := bitmap.Freeze()
        trW.Write(buf)
        // Proposed implementation allows:
        bitmap.WriteFrozenTo(trW)
    }
}
```

Except from real world usage, it sounds rather complicated to write a realistic benchmark for this. Any ideas of how to do that? Maybe I could fake that same usage with random bitmaps? Or maybe using the same one repeatedly, which would be easier.

I think I can have a better point when I collect the stats I promised tho.

**Comment by lemire** [comment]
I do not think that a performance benchmark is a requirement for us to update the code but I was reacting to your comment which alluded to efficiency.
