### ISSUE TITLE
roaring64 GetSizeInBytes error

### ISSUE THREAD

**Issue by hyhanyan** [RoaringBitmap/roaring#367]
type roaringArray64 struct {
      keys            []uint32
      containers      []*roaring.Bitmap
      needCopyOnWrite []bool
      copyOnWrite     bool
  }

func (rb *Bitmap) GetSizeInBytes() uint64 {
	size := uint64(8)
	for _, c := range rb.highlowcontainer.containers {
		size += uint64(2) + c.GetSizeInBytes()
	}
	return size
}
roaringArray64 keys is uint32，not uint16， GetSizeInBytes function  is

func (rb *Bitmap) GetSizeInBytes() uint64 {
	size := uint64(8)
	for _, c := range rb.highlowcontainer.containers {
		size += uint64(4) + c.GetSizeInBytes()
	}
	return size
}

**Comment by hyhanyan** [comment]
@jacobmarble  Have a look at it, thanks

**Comment by lemire** [comment]
@hyhanyan Would you consider issue a pull request to improve the function?

For context, here is the description of the function...

```Go
// GetSizeInBytes estimates the memory usage of the Bitmap. Note that this
// might differ slightly from the amount of bytes required for persistent storage
```

**Comment by hyhanyan** [comment]
> 

ok, I can do it

**Comment by hyhanyan** [comment]
> @hyhanyan Would you consider issue a pull request to improve the function?
> 
> For context, here is the description of the function...
> 
> ```go
> // GetSizeInBytes estimates the memory usage of the Bitmap. Note that this
> // might differ slightly from the amount of bytes required for persistent storage
> ```

https://github.com/RoaringBitmap/roaring/pull/368     please review it
