### ISSUE TITLE
upper bound memory estimate

### ISSUE THREAD

**Issue by patelprateek** [RoaringBitmap/roaring#369]
in the readme it mentions
```
Given N integers in [0,x), then the serialized size in bytes of a Roaring bitmap should never exceed this bound:

8 + 9 * ((long)x+65535)/65536 + 2 * N
```
After reading into some of the details , is my understanding correct that the upper bound memory usage should be
```
8 + 9 * ((long)x+65535)/65536 + min(2 * N , (long)x+65535)/65536 * 8KB)
```

**Comment by lemire** [comment]
The README provides an upper bound and refers to the software for more precise bounds. If you believe that the bound stated in the README us incorrect, please provide an example of a bitmap that would violate the bound.

To be clear, for the README to be proven incorrect, you need an example where the serialized size exceeds the stated upper bound.

The README does not claim that the bound is tight, only that it is an upper bound.

**Comment by patelprateek** [comment]
Sure , I didn't mean that it's incorrect , just a more tighter bound to make sure if my understanding is correct or am i missing something , since the current bound in readme gave an impression that it could possibly take a lot memory in some de-generate cases

**Comment by lemire** [comment]
There is a complicated and hard to read bound that is provided in software. The README provides a convenient bound that is easy to read.
