### ISSUE TITLE
question: what is Freeze?

### ISSUE THREAD

**Issue by xrfang** [RoaringBitmap/roaring#372]
I wonder what is the purpose of "Freeze()", from the code, it seems that it just output something to a []byte, there is no comments what-so-ever above this function in source code.

Also, what is the difference between WriteTo() and WriteFrozenTo()?   Thanks.

**Comment by lemire** [comment]
It is deliberate. We don't want regular users to use frozen serialization. The idea is to support immutable blobs of data that can be memory mapped. It was first created by the C version of roaring. Unless you work with memory mapping regularly, you probably do not want to look any further. If you do, then you should study the code. Using these functions is strictly at your own risks, we only offer minimal support.
