### ISSUE TITLE
Failed to read runtime container content: unexpected EOF

### ISSUE THREAD

**Issue by mpranab7890** [RoaringBitmap/roaring#376]
Been successfully using this library to track the range of numbers which are taken and returned for an application for few months now. 
However, suddenly encountered an error when reading bitmap from bytes this error and I couldn't find any solution for it. 

I encounter this error when I run
```
bitmap := roaring.New()
_, err = sa.AllIssuedShareNumbers.ReadFrom(bytes.NewReader(bytesArray))	

```

The err returned is 
`Failed to read runtime container content: unexpected EOF
`

I encounter this issue when _bytesArray_ is 
`[]byte{59, 48, 0, 0, 1, 0, 0, 90, 239, 191, 189, 3, 0, 1, 0, 120, 0, 239, 191, 189, 0, 239, 191, 189, 86, 49, 87, 60, 55}
`

**Comment by lemire** [comment]
Thanks for your comments.

The `ReadFrom` function should be called on a byte array that was created by `WriteTo`.

You must first serialize...

```Go
	// rb is your bitmap
        buf := &bytes.Buffer{}
	_, err := rb.WriteTo(buf)
```

Then you can load...

```Go
	newrb := NewBitmap()
	_, err = newrb.ReadFrom(buf)
```

If you encounter issues with a serialized output, please open a new issue. You should provide a fully reproducible case, starting with `WriteTo` and leading to `ReadFrom`.

I am going to close this for now.
