### ISSUE TITLE
Parallelize

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/roaring#38]
Roaring is ideally suited for parallel execution, as all containers can be operated upon in distinct threads.

**Comment by brentp** [comment]
do you have a model of how to do this? When doing, e.g. intersection, we would need to distribute the same blocks from each roaringbitmap to each thread (goroutine) but it could be that one of them is very dense and the other is very sparse.

**Comment by lemire** [comment]
I have ideas that we can discuss if you want, but there has been no experiment that I know of regarding parallelization, in Go or Java or... So this is research.

**Comment by gpunti** [comment]
Hi,

There's a version of MutableBitmap that can be accessed in parallel here ( is thread-safe ):

https://github.com/gpunti/RoaringBitmap/blob/thread-safety/src/main/java/org/roaringbitmap/ConcurrentBitmap.java

I still haven't asked for pull-request because I'm trying to figure out how to deal with the binary operations:  How to make a generic container interface so that all bitmap implementations (mutable, mapped, concurrent, etc...) comply, and then externalize the binary operations in separate classes that don't need to know about container implementations.

This is related on what you @brentp remarked on #37 regarding implementing intersects() only once.

**Comment by brentp** [comment]
@gpunti interesting. 
I was thinking you don't need a threadsafe container if you do the concurrency above the level of the container rather than within each container.

**Comment by lemire** [comment]
Right. I think that concurrency and parallelism are related but distinct here. The binary operations do not require concurrency in the sense that all you need to parallelize is the production of the containers... assembling the containers into a bitmap is cheap and can be single-threaded.

**Comment by gpunti** [comment]
That's right. This concurrent bitmap can work with any type of container. The problem are the binary operations, that are bitmap-implementation dependent. If we could made them independent ( with a shared container interface ) then we could have also have the same logic operations for any bitmap-implementation.

**Comment by lemire** [comment]
@gpunti 

(So we are clear, we are talking about Java code whereas tgruben/roaring is in Go.) 

> If we could made them independent ( with a shared container interface ) then we could have also have the same logic operations for any bitmap-implementation.

We already have something of the sort: the RoaringArray abstraction. That's how we were able to implement MutableRoaringBitmap and ImmutableRoaringBitmap. Whether you are in Go or in Java, the RoaringBitmap code itself does not specify a particular storage requirement. It is all handled by a separate class. This was by design, so that the logic would be isolated from the storage strategy. It comes at a small cost (e.g., extra memory usage), but makes it easier to code new features.

**Comment by gpunti** [comment]
If was thinking about doing something like this :

MutableBitmap mb = ...
ConcurrentBitmap cb = ...

OrOperator<ConcurrentBitmap> op = new OrOperator<ConcurrentBitmap> ( ConcurrentBitmapFactory )
ConcurrentBitmap result = op.execute ( mb, cb );

Probably the operation itself would become slower ( OrOperator could not take advantage of the container implementation details ) but would make everything more maintainable and operable. You could combine any type of bitmaps and receive them in your desired implementation.

Would that make sense to you? It would require quite a lot of work though

**Comment by lemire** [comment]
@gpunti 

Adding new code to do what you describe is probably fine. Users can then determine for themselves whether the eventual slowdown is worth it.

If what you have in mind, however, is to throw away the existing code and replace it with a whole new framework... well... it puts the bar high. The existing code is thoroughly tested, it runs on production servers, it is known to be fast enough... It is even more difficult if you break the API.

Maintainability is only a feature for people developing the library... for the users, it is not something worth sacrificing much for...

**Comment by gpunti** [comment]
@lemire Ok. I'll implement the binary operations and make the pull-requests for the whole concurrent solution. It won't be directly compatible with current bitmaps ( they will need some kind of conversion ) but I guess you're right and it's better to go step by step.
