### ISSUE TITLE
Add Bitmap.NextAbsentValue

### ISSUE THREAD

**Issue by ghost** [RoaringBitmap/roaring#380]
Java implementation has `nextAbsentValue` method. Go implementation doesn't. Could you please add it?

https://www.javadoc.io/doc/org.roaringbitmap/RoaringBitmap

```
public long nextAbsentValue​(int fromValue)

Returns the first absent value equal to or larger than
the provided value (interpreted as an unsigned integer).
It is not necessarily a computationally effective way
to iterate through the values.

Parameters:
    fromValue - the lower bound (inclusive)
Returns:
    the smallest absent value larger than or equal to
    the specified value.
```

**Comment by lemire** [comment]
That's a good issue. Do you want to try it out?

**Comment by lemire** [comment]
A PR is invited.

**Comment by opennota** [comment]
Looks like a lot of work. I don't think I need this method anymore, nor do I need the companion functions `previousAbsentValue`, `nextValue`, `previousValue`.

**Comment by lemire** [comment]
> Looks like a lot of work. 

It is not too bad, but it requires a minimum of care and a few hours.

**Comment by bearrito** [comment]
@lemire Once the validation stuff gets in I'll grab these. I think have a good enough grasp on the data structures to do this.

**Comment by bearrito** [comment]
Can be closed by linked issue.

**Comment by lemire** [comment]
Closed.
