### ISSUE TITLE
[roaring64] Why Or function modify bitmap "a" in this example?

### ISSUE THREAD

**Issue by zenxme** [RoaringBitmap/roaring#386]
According to the documentation: 

> Or computes the union between two bitmaps and stores the result in the current bitmap

But when you set a bitmap copyOnWrite, get a clone, and Or it, just like this example below:

```go
func Test() {
	a := roaring64.NewBitmap()
	for i := 0; i < 1000; i++ {
		a.Add(uint64(i))
	}
	a.SetCopyOnWrite(true)
	aClone := a.Clone()

	b := roaring64.NewBitmap()
	b.Add(1001)

	c := roaring64.NewBitmap()
	fmt.Println(c.GetCardinality(), a.GetCardinality(), aClone.GetCardinality(), b.GetCardinality())

	c.Or(aClone)
	c.Or(b) // modified bitmap a here

	fmt.Println(c.GetCardinality(), a.GetCardinality(), aClone.GetCardinality(), b.GetCardinality())

	fmt.Println(a.Contains(1001))
}
```

Output is :
```
0 1000 1000 1
1001 1001 1001 1
true
```

The documentation don't mention Or function whether modify parameter, is this is a bug or documentation incomplete?

**Comment by lemire** [comment]
> The documentation don't mention Or function whether modify parameter

You cited the documentation which clear states that the result is stored in the current bitmap.

I do not understand this issue.

**Comment by lemire** [comment]
Oh. Now I see it.

Yes. Looks like a bug.

**Comment by lemire** [comment]
I have marked this as a bug.

**Comment by lemire** [comment]
@guymolinari Can you have a look?

**Comment by guymolinari** [comment]
Yes.   Will do.

**Comment by lemire** [comment]
@zenxme Please update to the last release.

Note that you don't need roaring64 for this use case.

**Comment by zenxme** [comment]
> @zenxme Please update to the last release.
> 
> Note that you don't need roaring64 for this use case.

It' fixed now, thanks! I use roaring64 just for example, they are not real data.
