### ISSUE TITLE
Optimize the implementation of OrCardinality

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/roaring#40]
Currently, the OrCardinality function materializes temporary containers that are immediately (?) garbage collected. This is wasteful. Instead, we should have fast container-to-container union functions that just return the cardinality without doing memory allocation, as is the case with the intersections.

https://github.com/RoaringBitmap/roaring/blob/db18267a1ca5d1d4c9a91c23d585b1ce8e255e45/roaring.go#L416

c.c. @tgruben  @statik @bpot @tvmaly

**Comment by statik** [comment]
@lemire I started taking a look at this and got a little confused. I'll list out what I found, and just say there is a good chance I'm missing something and would greatly appreciate any pointers on what operations are still missing here.

https://github.com/RoaringBitmap/roaring/blob/master/setutil.go#L211 has `intersects2by2`. Not sure if the 2by2 suffix is correct, when comparing https://github.com/RoaringBitmap/RoaringBitmap/blob/50d435c5f82df78b5d369f4120559e10c3455e95/src/main/java/org/roaringbitmap/Util.java#L680

`intersects2by2` is called from https://github.com/RoaringBitmap/roaring/blob/b747b1bc3116266fd63238c4eb46088ac7408b13/arraycontainer.go#L647 which seems similar to the way it is used in java https://github.com/RoaringBitmap/RoaringBitmap/blob/78ad3a1c11e374e471e4fc666257569269447412/src/main/java/org/roaringbitmap/ArrayContainer.java#L573

I also see OrCardinality, AndCardinality, and Intersects implemented herev in the public API:
https://github.com/RoaringBitmap/roaring/blob/db18267a1ca5d1d4c9a91c23d585b1ce8e255e45/roaring.go#L387
https://github.com/RoaringBitmap/roaring/blob/db18267a1ca5d1d4c9a91c23d585b1ce8e255e45/roaring.go#L441
https://github.com/RoaringBitmap/roaring/blob/db18267a1ca5d1d4c9a91c23d585b1ce8e255e45/roaring.go#L488

**Comment by lemire** [comment]
@statik  I'll get back to you.

**Comment by lemire** [comment]
@statik 



> Not sure if the 2by2 suffix is correct

It means that we take the intersection of two sets... as opposed to intersecting 3 sets, and so forth. Arguably, the 2by2 suffix is unnecessary but that's a private function.

**Comment by lemire** [comment]
@statik 

Ok. So the current status of this issue is that it is all implemented *except* that the ``OrCardinality `` function materializes the temporary containers needlessly.

https://github.com/RoaringBitmap/roaring/blob/db18267a1ca5d1d4c9a91c23d585b1ce8e255e45/roaring.go#L416

I'll update the issue description to avoid confusion.

**Comment by lemire** [comment]
@statik 

Done. Let us hope that things are clearer now. Thanks for the feedback.

**Comment by statik** [comment]
@lemire thanks! this makes sense. I hope to find some time to work on this.

**Comment by lemire** [comment]
@statik  Please do. And, also, if you do, don't forget to throw in extra tests for good measure!

**Comment by lemire** [comment]
Resolved as of this commit https://github.com/RoaringBitmap/roaring/commit/8a91ca43880d9ef48f8f28750f1fb4c65e29c509
