### ISSUE TITLE
error in roaringArray.readFrom: did not find expected serialCookie in header

### ISSUE THREAD

**Issue by Akhilesh53** [RoaringBitmap/roaring#401]
I am getting this error while running code. 

Bytes Array : [12 153 189 3 223 1 161 4 110 103 121 173 12 253 195 3 206 5]

When I was using badger, it worked fine. But now I switched the cockroachdb/pebble. Now it is giving this error.

**Comment by Akhilesh53** [comment]
Is there any other way to add serialCookie separately?

**Comment by lemire** [comment]
Please make sure that the data follows the format specified at 

https://github.com/RoaringBitmap/RoaringFormatSpec

It is obvious that the input your provide does not follow this specification.

> When I was using badger, it worked fine.

My understanding is that Dgraph use their own custom data formats. If you are a Dgraph customer and need to export your data to the standard Roaring format, you should reach out to Dgraph.

If you'd like to contribute code to `roaring` to add the ability to import Dgraph data, we invite pull requests.

I am closing this issue.
