### ISSUE TITLE
 "error in roaringArray.readFrom: did not find expected serialCookie in header"

### ISSUE THREAD

**Issue by Akhilesh53** [RoaringBitmap/roaring#402]
Error is coming at line no 104. 

<img width="871" alt="image" src="https://github.com/RoaringBitmap/roaring/assets/64018679/b7ca3db9-8b09-4ac6-b876-aba0a7d5dcc9">

This is the func definition which is returning []byte from cockroach/pebble db. 

<img width="642" alt="image" src="https://github.com/RoaringBitmap/roaring/assets/64018679/ae1eec5c-a479-4f9e-99eb-b3eb5c294dcf">

The same error is occurring here too. 

<img width="1003" alt="Screenshot 2023-09-30 at 12 04 21 PM" src="https://github.com/RoaringBitmap/roaring/assets/64018679/123ad737-099c-4d19-837c-8f19ee62bc14">

Sending the values in the channel from here (see the below pic) :

<img width="870" alt="image" src="https://github.com/RoaringBitmap/roaring/assets/64018679/f29f8494-6905-465a-9b43-7e822f2be013">

Also getting this error.

```
panic: runtime error: index out of range [8097] with length 8097

goroutine 12336330 [running]:
github.com/RoaringBitmap/roaring.(*bitmapContainer).fillLeastSignificant16bits(0xc00a93b540, {0xc0069da000, 0x1fa1, 0xc004424680?}, 0xc006c98300?, 0x0?)
        /data/badger_broadband/badger_grpc/vendor/github.com/RoaringBitmap/roaring/bitmapcontainer.go:275 +0xdd
github.com/RoaringBitmap/roaring.(*Bitmap).ToArray(0xc001c43ea0)
        /data/badger_broadband/badger_grpc/vendor/github.com/RoaringBitmap/roaring/roaring.go:232 +0xbd
cluster/models.(*MisraGries).ProcessStream(0xb73360?, 0xc003dfaae0?, 0xc00081d7b8?)
        /data/badger_broadband/badger_grpc/models/misragries.go:28 +0x85
created by cluster/badger_cluster.(*Address).FindClusterForNewAddress in goroutine 5692
        /data/badger_broadband/badger_grpc/badger_cluster/address.go:69 +0x1f1

```

This error occurs frequently, But the same did not happen while using Badger.
Please help me out. 
Please keep the comments section open so that I can ask any other doubts.

**Comment by lemire** [comment]
Sorry but I am closing this issue as it is invalid.

You must show that your inputs follow the Roaring specification which explicitly documented:
https://github.com/RoaringBitmap/RoaringFormatSpec

As I wrote in the previous issue, badger use their own custom implementation: https://github.com/dgraph-io/sroar

That is fine but if you encounter format incompatibilities with standard Roaring bitmaps, then reach out to Dgraph.

We only support the roaring library and the standard Roaring format.

You can use customized implementations but we will not support it.

You can, of course, suggest pull requests to use with new functionality to accommodate your needs.

Of course, it is possible that we have bugs. If so, please provide analysis and test cases. 

Your bug report should not involve serialized data by another library we do not support. If this other library was meant to produce standard Roaring bitmaps, then issue a bug report with them, using the specification.

If you have standard compliant inputs that we fail to deserialize properly, please demonstrate that your serialized data is compliant with our format and open a bug report with such data. Note that I consider such bugs unlikely.

**Comment by Akhilesh53** [comment]
Agreed. But the point is whatever values we are storing in the bitmap, we are storing the same in db as []byte and fetching the same []byte from memory and writing it back in the bitmap. If the values stored in the bitmap are valid, it should not give an error. @lemire

**Comment by lemire** [comment]
Then you should be able to reproduce the issue using a standard compliant input. Please make sure to document how it follows the standard. Provide reproducible code.

**Comment by lemire** [comment]
Let me elaborate...

> If the values stored in the bitmap are valid

That's the critical part. You have to prove that it is the case. You have to see whether they are standard compliant. Most likely, they are not.
