### ISSUE TITLE
Go get error

### ISSUE THREAD

**Issue by mvestnik** [RoaringBitmap/roaring#415]
![Screenshot from 2024-03-08 20-36-08.png](https://github.com/RoaringBitmap/roaring/assets/150515091/29c7f833-d33b-4dfd-a666-ccb8845df6a2)

**Comment by mvestnik** [comment]
Exporting the env var helped:
```go
export GO PROXY=direct
```
But it's very slooow to install

**Comment by lemire** [comment]
The files are provided by GitHub, and we have no control over the performance or the network connectivity. However, you can build local repositories and bypass GitHub.
