### ISSUE TITLE
Different 32 and 64 versions

### ISSUE THREAD

**Issue by mvestnik** [RoaringBitmap/roaring#439]
Why are 32 and 64 versions different and will the ParAnd or FastParAnd method be implemented in the 64 version?

**Comment by lemire** [comment]
> Why are 32 and 64 versions different

They are different data structures. It depends on your needs. I encourage you to run benchmarks.

> will the ParAnd or FastParAnd method be implemented in the 64 version?

The project is a community-based project. Please consider providing a pull request.
