### ISSUE TITLE
Hi all, I see the static RoaringBitmap.and and .or but I can't find equivalents for 64-bit, do they exist?

### ISSUE THREAD

**Issue by xq182** [RoaringBitmap/roaring#449]
Hi all, I see the static RoaringBitmap.and and .or but I can't find equivalents for 64-bit, do they exist?

**Comment by lemire** [comment]
Much of the functionality for 64-bit roaring bitmaps is found in `roaring64.go`.

https://github.com/RoaringBitmap/roaring/blob/205a16764a30252a9e17b1faa3fdb6996b817815/roaring64/roaring64.go#L676

https://github.com/RoaringBitmap/roaring/blob/205a16764a30252a9e17b1faa3fdb6996b817815/roaring64/roaring64.go#L831

You can also refer to the documentation ... see https://pkg.go.dev/github.com/RoaringBitmap/roaring/v2/roaring64#And
