### ISSUE TITLE
use arrays for dense blocks

### ISSUE THREAD

**Issue by brentp** [RoaringBitmap/roaring#47]
the cython implementation by @andreasvc has a nice idea from lucene "that it uses arrays not only when a block contains less than 2 *\* 12 elements, but also when it contains more than 2 *\* 32 - 2 *\* 12 elements; i.e., blocks that are mostly full are stored just as compactly as blocks that are mostly empty"

it would be nice to support that in this version.

**Comment by lemire** [comment]
Alternatively, one can use 

https://github.com/tgruben/roaring/issues/37

**Comment by lemire** [comment]
Note that run containers have proven beneficial in practice, in Apache Spark and in Druid... greatly reducing memory usage in important cases. 

I am not convinced that the benefits of the proposed enhancement are as large and as general.

**Comment by lemire** [comment]
As of 0.3.0, this library has run containers which I think partly addresses this issue.

**Comment by maciej** [comment]
@lemire I was looking at some of the older issues and found this one. Is support for _inverse_ array containers still considered? Could we close this issue if not?

**Comment by lemire** [comment]
I think that this issue could be closed, yes. Do you support closing it?

**Comment by brentp** [comment]
closing
