### ISSUE TITLE
Flip on an empty bitmap does not set bits

### ISSUE THREAD

**Issue by joenall** [RoaringBitmap/roaring#50]
package main

import (
        "fmt"
        "github.com/roaring"
)

func main() {
        bm := roaring.NewRoaringBitmap()
        roaring.Flip(bm, 0, 10)
        fmt.Printf("%v cardinality is: %d\n", bm, bm.GetCardinality())
}

**Comment by lemire** [comment]
@joenall 

Correct code would be 

```
package main

import (
"fmt"
"github.com/roaring"
)

func main() {
bm := roaring.NewRoaringBitmap()
bm = roaring.Flip(0, 10)
fmt.Printf("%v cardinality is: %d\n", bm, bm.GetCardinality())
}
```


Or better yet, if you do not want to generate too many new objects...

```
package main

import (
"fmt"
"github.com/roaring"
)

func main() {
bm := roaring.NewRoaringBitmap()
bm.Flip(0, 10)
fmt.Printf("%v cardinality is: %d\n", bm, bm.GetCardinality())
}
```

The documentation seems correct and I have added new unit tests.

Thanks for the report. I will close this, reopen if you disagree.
