### ISSUE TITLE
Difference between and and fastAnd, and fellows

### ISSUE THREAD

**Issue by anacrolix** [RoaringBitmap/roaring#51]
There are several methods with "fast" variants. Other than a minor interface change, what do they differently? Can you document this?

**Comment by lemire** [comment]
Thanks.

Documentation is improved... e.g., see  

https://godoc.org/github.com/RoaringBitmap/roaring#FastOr

Closing. Re-open if you disagree.

**Comment by anacrolix** [comment]
Great, thanks.
