### ISSUE TITLE
[Proposal] start tagging semver releases

### ISSUE THREAD

**Issue by kron4eg** [RoaringBitmap/roaring#52]
It would help a lot if this repo will start using http://semver.org spec. Simple `git tag v0.1.0`.

**Comment by lemire** [comment]
Having formal releases is certainly something we should do.

However, it should also be aligned on the Go ecosystem. If you can't declare as a dependency specific versions, it is somewhat irrelevant that you have versions at all... 

In Java, at https://github.com/RoaringBitmap/RoaringBitmap/tags, versions are tagged automatically with Maven and projects can require any one specific version, using a standard Maven dependency. The Maven tags follow the ```Name-major-minor-patch``` convention.

I think we should use whatever release convention that is best supported by the Go tools. If there is no support yet for release versions, then I think we should wait for such support to emerge.

Thoughts?

**Comment by kron4eg** [comment]
At the moment "official" way of doing versioning in Go is — vendoring. In Go 1.5 Go vendor experiment was introduced and in 1.6 it became on by default. And virtually all vendoring tools could fetch dependencies based on git refs, like tags/branches and so on.

So simple git tags will be more then enough.

**Comment by lemire** [comment]
@kron4eg 

Done. Reopen if you disagree.
