### ISSUE TITLE
Consider renaming from roaring.RoaringBitmap to roaring.Bitmap

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/roaring#54]
Golint warning makes sense to me... but this would break existing code... 

``` type name will be used as roaring.RoaringBitmap by other packages, and that stutters; consider calling this Bitmap```

**Comment by kron4eg** [comment]
This package is imported only by one public package: https://godoc.org/github.com/RoaringBitmap/roaring?importers , so rename will not that catastrophic

**Comment by lemire** [comment]
@kron4eg 

Thanks.

I'd like us to collect more feedback before we make this change, if possible. Lots of dependencies could exist within private projects.

c.c. @brentp @willglynn  @bpot @tvmaly @boutros @statik

**Comment by brentp** [comment]
+1 for change.

**Comment by willglynn** [comment]
+1 from me.

**Comment by boutros** [comment]
Sounds good too me. No problem updating my projects using it

**Comment by statik** [comment]
+1 for the name change.

**Comment by lemire** [comment]
Named changed. Bumped the version to 0.2.0.

Thanks to all for giving feedback.

**Comment by anacrolix** [comment]
How am I the only public user! And I just wrap it anyway. Also godoc only tracks packages that have been viewed there, so public packages may exist that just haven't been godoc'd? Either way cool change.
