### ISSUE TITLE
possible Flip() bug?

### ISSUE THREAD

**Issue by steveyen** [RoaringBitmap/roaring#64]
Hi, thanks for the cool work on roaring bitmaps.

Here's something strange that I originally encountered while trying to write some automated fuzz testing for roaring.

It's possible I'm using the Flip() API incorrectly, or the bug is really in the willf.BitSet that I'm comparing roaring against, but please see here for a simple test...

https://github.com/steveyen/roaring/blob/master/roaring_test.go#L1685
```
		bm := roaring.NewBitmap()
		bs := bitset.New(0)

		bm.AddInt(0)
		bs = bs.Set(0)

		bm.Flip(1, 2)
		bs = bs.Flip(1)

		So(equalsBitSet(bs, bm), ShouldEqual, true) // Fails here.
}
```

**Comment by lemire** [comment]
Yes. Good catch. Fixed in v0.2.8. See unit test I added: https://github.com/RoaringBitmap/roaring/blob/master/roaring_test.go#L12-L32

**Comment by lemire** [comment]
Please keep hunting for bugs!

**Comment by lemire** [comment]
Please considering issuing a PR with your new tests. We never have enough good tests!
