### ISSUE TITLE
Q: recommended way to intersect with a contiguous interval/time span?

### ISSUE THREAD

**Issue by glycerine** [RoaringBitmap/roaring#69]
A common filter, used in 90% of my queries, is to restrict a document set to a [begin,end) interval or time-window. 

If I was to construct document IDs in chronological order, then this filter can be efficiently represented by a [first, last) interval of two integers.

Q: what is the efficient way to represent/construct such a bitset in Roaring, and use it in intersections?

Wrinkle: I typically have 100e6 documents, so it seems super inefficient (but please correct me if I'm wrong) to do the following:
```
func CreateContinguousSpanBitmap(begTime, endTime uint64, chronoOrderedDocs []Doc) *roaring.Bitmap {
 b := roaring.NewBitmap()
 n := len(chronoOrderedDocs)
 for i:=uint32(0); i <  n; i++ {
   b.Add(i)
 }
 b.RemoveRange(begTime, endTime) 
 b.Flip(0, n)
 return b
}
```

There's got to be a faster way, no?

**Comment by glycerine** [comment]
Reading https://arxiv.org/pdf/1603.06549v3.pdf, this looks like a perfect use of the Roaring+Run encoding. Is Roaring+Run available in the Go (or, if need by, the C/C++) version of roaring?

**Comment by glycerine** [comment]
looks like this is #37, so not yet implemented. I'll see about porting the Java code to Go.

**Comment by brentp** [comment]
@glycerine also see my start here: https://github.com/RoaringBitmap/roaring/issues/37#issuecomment-173615900

**Comment by glycerine** [comment]
closing in favor of #37. Initial functionality in #70
