### ISSUE TITLE
runContainer16 efficiency: avoid O(N^2) in runContainer16 interval subtraction

### ISSUE THREAD

**Issue by glycerine** [RoaringBitmap/roaring#72]
https://github.com/RoaringBitmap/roaring/pull/70/files#diff-fd38fd3c1b1dffc8f36af21de50228f5R1204

line 1203 of rle16.go, at the top of isubtract() I make a copy of the backing slice rc.iv:
```
func (rc *runContainer16) isubtract(del interval16) {
	origiv := make([]interval16, len(rc.iv))
	copy(origiv, rc.iv)
       ...
```

The copy of rc.iv into origiv is needed for correctness, because subtracting an interval can actually split an existing interval in two and make the overall slice grow.

Hence under the current implementation using a backing slice of intervals, a pathological subtraction of a set of intervals could cause O(N^2) time. For large sets a red-black tree, e.g. https://github.com/glycerine/rbtree, or converting to a bitmapContainer first and doing the subtraction there, is probably faster; but needs to be measured.

**Comment by lemire** [comment]
@glycerine  Wouldn't the right solution to use the fact that size and capacity are distinct values in Go arrays? So you check whether the capacity is large enough, and you reallocate only if the capacity is insufficient. When you do reallocate, you always grow the capacity by a multiplicative factor (say ``2*`` or less).

**Comment by glycerine** [comment]
This isn't really a storage issue, but rather a time one. The concern is about the time complexity of repeated inserting a new element into the middle of a length N array. It costs O(N) time each time to copy (even just) the tail and make room in the middle. A set A - B subtraction could do O(N) such operations. Hence the O(N^2) time complexity.

**Comment by lemire** [comment]
@glycerine 

Obviously, we can't implement set subtraction using repeated calls to a linear-time function.

Here is the corresponding function in C:

https://github.com/RoaringBitmap/CRoaring/blob/master/src/containers/run.c#L435-L496

**Comment by glycerine** [comment]
There is definitely room for efficiency optimizations in my stuff.

That said, I don't think that's the corresponding function, as it says:

```/* Compute the difference of src_1 and src_2 and write the result to
 * dst. It is assumed that dst is distinct from both src_1 and src_2. */
void run_container_andnot(const run_container_t *src_1,
                          const run_container_t *src_2, run_container_t *dst) {
```

In contrast, isubtract() is in-place, so dst would be the same as one of src_1 or src_2.

Currently I expand to bitmapContainers for iandnot... https://github.com/glycerine/roaring/blob/master/rlei.go#L416

Definitely one of those cases that wants more optimization than my initial pass gave it.

I don't see any inplace functions in the C. If that has proved fast enough, it sure would be simpler go Go too; this api has alot of surface.

**Comment by lemire** [comment]
If we need to reallocate the memory, we are no longer processing the data in-place, so we might as well create a new container and write the answer there... We'll get linear-time complexity and a single memory allocation.

I submit to you the isubtract is not in-place.

Of course, we get into semantics... but I think you'll see what I mean when I choose to equate in-place with the absence of non-trivial memory allocation.

I have not checked your implementation yet... for all I know, it is perfect. I am just reacting to the issue at a high level.

**Comment by glycerine** [comment]
I addressed my concern about the gross memory over allocation in 4c1ebfed0b16eb2e1074ca5ec662907767dc9333, and I added a port of C's run_container_andnot in 9ecb8d537bcde76f51ca8b5963cf767096642ab9.

There's plenty of additional tuning the runContainers could take, but the issues mentioned here have been addressed so I'll close this out.
