### ISSUE TITLE
thoughts on serialization formats

### ISSUE THREAD

**Issue by glycerine** [RoaringBitmap/roaring#76]
Thoughts on serialization... things that could save a bunch of time...

When I need quick and portable serialization, I typically use msgpack2 from http://msgpack.org. It's a binary version of JSON that has a readable spec and is portable to all languages.

A reason I like msgpack2: there is an easy to use library for Go that is very fast.
Fast to deploy and fast when reading/writing.

https://github.com/tinylib/msgp in particular will parse your .go files and do codegen for your Go structs, making setting up serialization a 30 second task. All that is required is that your struct fields be Exported (capitalized).

Usually compression isn't needed afterwards, depending on the entropy of your data. You have to measure, but sometimes it is a win. If desired, then snappy can be easily applied without sacrificing decoding speed. Other general purpose compressors like gzip and bzip will sometimes compress slightly more, but are super slow to decode, hogging cpu and wasting valuable time at runtime. I usually use my implementation of the streaming snappy format here, https://github.com/glycerine/go-unsnap-stream, as it comes with nice command line tools (snap and unsnap).  Since Google open sourced snapped (http://google.github.io/snappy/) quite a while ago, there are libraries for most languages for this as well.

Finally, one other nice thing about msgpack2 is that you don't need to predefine a schema; like JSON the data is self describing. It gives you some data-evolution capability (based of field names rather than field numbers) while being dynamic language friendly. There is no need for a pre-compiler (as in protobufs/thrift/capnproto) and java and python can read msgpack2 with the available libraries. msgpack2 is quite a bit more strongly typed that JSON however, and you can quickly move binary data without a whole lot of base64 encoding fuss.

That said, if one really wants a schema for future proofing the data evolution, then protobufs are also highly tuned and have libraries for the big 4 (Go, C++, Java, python).  Also I used to maintain a capnproto implementation for Go, so I can discuss that if it is of interest. However the java bindings were never finished, so I didn't really consider capnproto a choice here where java support is expected.

**Comment by lemire** [comment]
@glycerine  Is this issue still relevant as stated?

**Comment by glycerine** [comment]
both formats are now available. We can close this out!
