### ISSUE TITLE
Int overflow?

### ISSUE THREAD

**Issue by 0x4139** [RoaringBitmap/roaring#85]
doesn't this overflow int?
https://github.com/RoaringBitmap/roaring/blob/master/util.go#L283

**Comment by 0x4139** [comment]
i think it should be `rand.Intn((1 << 30)-1)`

**Comment by lemire** [comment]
@0x4139 
 
I think that @glycerine  assumed that we are working on a 64-bit system. (???)

**Comment by 0x4139** [comment]
@lemire yep

**Comment by 0x4139** [comment]
@glycerine can you explain why `1 << 29` and not (1<<31)-1 being the largest number on 32 bit systems?

**Comment by lemire** [comment]
@0x4139  @glycerine I'm pretty sure that the answer is ``(1<<31)-1`` though it is maybe better expressed as ``0x7fffffff`` (matter of taste).

**Comment by glycerine** [comment]
@0x4139 It doesn't matter for correctness, and the point is to look at it and quickly know that it doesn't overflow int even on 32-bit systems.
