### ISSUE TITLE
build conditionals and serialization : functions uint64SliceAsByteSlice and uint16SliceAsByteSlice should be "file private" to  serialization_littleendian.go and never be called elsewhere.

### ISSUE THREAD

**Issue by 0x4139** [RoaringBitmap/roaring#86]
if someone will try to build this library for other platforms `uint64SliceAsByteSlice` and `uint16SliceAsByteSlice` will cause errors

**Comment by lemire** [comment]
We need someone to test and debug the code on a big endian machine.

**Comment by lemire** [comment]
c.c. @glycerine
