### ISSUE TITLE
rle.go has low test coverage

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/roaring#88]
File ``rle.go`` has a test coverage of only 70%: https://coveralls.io/jobs/21261570/source_files/124780022

**Comment by glycerine** [comment]
Yes. The reason is that it isn't really used at this point. It's there to support future studies. If the low coverage concerns anyone, then I suggest we simply turn off coverage reporting on it.

**Comment by lemire** [comment]
@glycerine  To do this, do you have anything more clever than this answer...

http://stackoverflow.com/questions/25511076/ignore-code-blocks-in-golang-test-coverage-calculation

**Comment by glycerine** [comment]
just add it to the list here:
https://github.com/RoaringBitmap/roaring/blob/master/.travis.yml#L17
