### ISSUE TITLE
Build fails for ARM architecture (maybe anything other than amd64?)

### ISSUE THREAD

**Issue by cvermilion** [RoaringBitmap/roaring#89]
I don't know if this an architecture you care about targeting, but it's one my company has been using, and it looks like #84 broke building there. (We use `gomobile` to build a library that we use on iOS.)

Here are the errors I get running `GOARCH=arm64 go build` in my project that uses this library:

```
# github.com/figly/datasearch/vendor/github.com/RoaringBitmap/roaring
../vendor/github.com/RoaringBitmap/roaring/ctz_generic.go:52: undefined: deBruijn64Lookup
../vendor/github.com/RoaringBitmap/roaring/ctz_generic.go:52: undefined: deBruijn64
../vendor/github.com/RoaringBitmap/roaring/serialization_generic.go:56: undefined: buf
```

The last error looks like a pretty simple variable name typo, but I'm not sure what the right fix is for the first two.

**Comment by lemire** [comment]
We definitively want to support all platforms.

**Comment by lemire** [comment]
@glycerine want to have a look?

**Comment by glycerine** [comment]
sure, just sec

**Comment by lemire** [comment]
@cvermilion  Please verify that this issue has been fixed.

**Comment by cvermilion** [comment]
@lemire Looks good to me! I was about to suggest that you add cross-compilation to CI, too, but then I saw you already tackled that in #91. Thanks for the quick fix!

**Comment by lemire** [comment]
@cvermilion  To be fair, the issue was fixed by @glycerine not me. :-)
